//! One row per `DXGI_FORMAT`, behind the predicates that used to be eight
//! independent range tables.
//!
//! Eight hand-written `match` trees classified the same DXGI_FORMAT integer
//! space with partly overlapping arms keyed on raw numbers. Adding a format to
//! one and not the others yields an incoherent caps answer — resolvable but not
//! MSAA-capable, say — which the D3D11 runtime rejects as one feature-level
//! contract during `CDevice::LLOCompleteLayerConstruction`, not as a per-format
//! problem. The three known divergences between `bits_per_sample` and
//! `output_family_bits` were undocumented and indistinguishable from drift.
//!
//! This module is a lookup table plus thin readers. **There is no type-level
//! guarantee here**: `DXGI_FORMAT` stays an integer and the table is indexed by
//! number. The deliverable is that every format's answers sit on one row, and
//! that the `0..=200` equivalence test below pins every one of them to the
//! pre-change predicate.
//!
//! The rows were generated by compiling the original eight `match` bodies and
//! printing their answers for 0..116, not transcribed by hand. The test module
//! keeps those original bodies verbatim as `legacy_*` and asserts the table
//! agrees over `0..=200` — which also covers the out-of-table tail, where the
//! defaults (4 bytes per pixel, everything else absent/false) must still apply.
//!
//! It is deliberately free of `windows`-crate and WDK types so
//! `tools/format-table-check.rs` can `include!` it and run the equivalence test
//! on the Linux host in seconds. `helios_umd` itself is a `cdylib` with
//! `panic = "abort"` and no test harness.

/// Every classification of one DXGI format, in one row.
#[derive(Clone, Copy)]
pub(crate) struct FormatInfo {
    /// Bytes per pixel for WDDM surface-pitch arithmetic. 4 is the default for
    /// everything not explicitly sized, including the 16-bpp B5G6R5 /
    /// B5G5R5A1 / B4G4R4A4 formats and every block-compressed format:
    /// over-reporting only pads `linear_size`, where under-reporting an A8
    /// mask as 4 bpp sized those surfaces 4x too large.
    bytes_per_pixel: u8,
    /// Bits per sample for the uncompressed formats that can take part in
    /// D3D11 output/MSAA validation. Compressed and video-only formats are
    /// deliberately absent so the runtime does not require MSAA for them.
    bits_per_sample: Option<u8>,
    /// The same question asked of the format's *family*, used when the format
    /// carries neither the RENDER_TARGET nor the DEPTH_STENCIL support bit.
    ///
    /// It differs from `bits_per_sample` in exactly three places, all visible
    /// as rows here rather than as an unexplained range mismatch:
    ///   - 65 (`R1_UNORM`): sized as a sample, no output family.
    ///   - 85, 86, 115 (`B5G6R5`, `B5G5R5A1`, `B4G4R4A4`): 16-bit samples,
    ///     no output family.
    ///   - 89 (`B8G8R8X8_UNORM`): a 32-bit sample, no output family.
    output_family_bits: Option<u8>,
    /// Depth-resource read/view formats are format-support siblings of the
    /// MSAA-capable typeless/depth formats, but WARP reports zero quality
    /// levels above 1x and the runtime rejects advertising them as MSAA render
    /// targets.
    msaa_ineligible: bool,
    /// The format, or a typeless parent of it, has at least one resolvable
    /// UNORM/SNORM/FLOAT interpretation.
    resolve_required: bool,
    /// A colour typeless parent.
    color_typeless_parent: bool,
    /// An integer-typed (UINT/SINT) format.
    integer_typed: bool,
}

const fn row(
    bytes_per_pixel: u8,
    bits_per_sample: Option<u8>,
    output_family_bits: Option<u8>,
    msaa_ineligible: bool,
    resolve_required: bool,
    color_typeless_parent: bool,
    integer_typed: bool,
) -> FormatInfo {
    FormatInfo {
        bytes_per_pixel,
        bits_per_sample,
        output_family_bits,
        msaa_ineligible,
        resolve_required,
        color_typeless_parent,
        integer_typed,
    }
}

/// The row used for every format number at or past the end of the table.
///
/// This is not padding: DXGI defines formats past 115 (the video and
/// ASTC/BC ranges), and the pre-change predicates answered exactly this for
/// all of them.
const DEFAULT_ROW: FormatInfo = row(4, None, None, false, false, false, false);

/// One row per DXGI format number, 0..=115.
const FORMAT_TABLE: [FormatInfo; 116] = [
    /*   0 */ row(4, None, None, false, false, false, false),
    /*   1 */ row(16, Some(128), Some(128), false, true, true, false),
    /*   2 */ row(16, Some(128), Some(128), false, true, false, false),
    /*   3 */ row(16, Some(128), Some(128), false, false, false, true),
    /*   4 */ row(16, Some(128), Some(128), false, false, false, true),
    /*   5 */ row(12, Some(96), Some(96), false, true, true, false),
    /*   6 */ row(12, Some(96), Some(96), false, true, false, false),
    /*   7 */ row(12, Some(96), Some(96), false, false, false, true),
    /*   8 */ row(12, Some(96), Some(96), false, false, false, true),
    /*   9 */ row(8, Some(64), Some(64), false, true, true, false),
    /*  10 */ row(8, Some(64), Some(64), false, true, false, false),
    /*  11 */ row(8, Some(64), Some(64), false, true, false, false),
    /*  12 */ row(8, Some(64), Some(64), false, false, false, true),
    /*  13 */ row(8, Some(64), Some(64), false, true, false, false),
    /*  14 */ row(8, Some(64), Some(64), false, false, false, true),
    /*  15 */ row(8, Some(64), Some(64), false, true, true, false),
    /*  16 */ row(8, Some(64), Some(64), false, true, false, false),
    /*  17 */ row(8, Some(64), Some(64), false, false, false, true),
    /*  18 */ row(8, Some(64), Some(64), false, false, false, true),
    /*  19 */ row(8, Some(64), Some(64), false, true, false, false),
    /*  20 */ row(4, Some(64), Some(64), false, false, false, false),
    /*  21 */ row(4, Some(64), Some(64), true, false, false, false),
    /*  22 */ row(4, Some(64), Some(64), true, false, false, false),
    /*  23 */ row(4, Some(32), Some(32), false, true, true, false),
    /*  24 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  25 */ row(4, Some(32), Some(32), false, false, false, true),
    /*  26 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  27 */ row(4, Some(32), Some(32), false, true, true, false),
    /*  28 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  29 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  30 */ row(4, Some(32), Some(32), false, false, false, true),
    /*  31 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  32 */ row(4, Some(32), Some(32), false, false, false, true),
    /*  33 */ row(4, Some(32), Some(32), false, true, true, false),
    /*  34 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  35 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  36 */ row(4, Some(32), Some(32), false, false, false, true),
    /*  37 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  38 */ row(4, Some(32), Some(32), false, false, false, true),
    /*  39 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  40 */ row(4, Some(32), Some(32), false, false, false, false),
    /*  41 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  42 */ row(4, Some(32), Some(32), false, false, false, true),
    /*  43 */ row(4, Some(32), Some(32), false, false, false, true),
    /*  44 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  45 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  46 */ row(4, Some(32), Some(32), true, true, false, false),
    /*  47 */ row(4, Some(32), Some(32), true, false, false, false),
    /*  48 */ row(4, Some(16), Some(16), false, true, true, false),
    /*  49 */ row(4, Some(16), Some(16), false, true, false, false),
    /*  50 */ row(4, Some(16), Some(16), false, false, false, true),
    /*  51 */ row(4, Some(16), Some(16), false, true, false, false),
    /*  52 */ row(4, Some(16), Some(16), false, false, false, true),
    /*  53 */ row(4, Some(16), Some(16), false, true, true, false),
    /*  54 */ row(4, Some(16), Some(16), false, true, false, false),
    /*  55 */ row(4, Some(16), Some(16), false, true, false, false),
    /*  56 */ row(4, Some(16), Some(16), false, true, false, false),
    /*  57 */ row(4, Some(16), Some(16), false, false, false, true),
    /*  58 */ row(4, Some(16), Some(16), false, true, false, false),
    /*  59 */ row(4, Some(16), Some(16), false, false, false, true),
    /*  60 */ row(1, Some(8), Some(8), false, true, true, false),
    /*  61 */ row(1, Some(8), Some(8), false, true, false, false),
    /*  62 */ row(1, Some(8), Some(8), false, false, false, true),
    /*  63 */ row(1, Some(8), Some(8), false, true, false, false),
    /*  64 */ row(1, Some(8), Some(8), false, false, false, true),
    /*  65 */ row(1, Some(8), None, false, false, false, false),
    /*  66 */ row(1, None, None, false, false, false, false),
    /*  67 */ row(4, None, None, false, false, false, false),
    /*  68 */ row(4, None, None, false, false, false, false),
    /*  69 */ row(4, None, None, false, false, false, false),
    /*  70 */ row(4, None, None, false, false, false, false),
    /*  71 */ row(4, None, None, false, false, false, false),
    /*  72 */ row(4, None, None, false, false, false, false),
    /*  73 */ row(4, None, None, false, false, false, false),
    /*  74 */ row(4, None, None, false, false, false, false),
    /*  75 */ row(4, None, None, false, false, false, false),
    /*  76 */ row(4, None, None, false, false, false, false),
    /*  77 */ row(4, None, None, false, false, false, false),
    /*  78 */ row(4, None, None, false, false, false, false),
    /*  79 */ row(4, None, None, false, false, false, false),
    /*  80 */ row(4, None, None, false, false, false, false),
    /*  81 */ row(4, None, None, false, false, false, false),
    /*  82 */ row(4, None, None, false, false, false, false),
    /*  83 */ row(4, None, None, false, false, false, false),
    /*  84 */ row(4, None, None, false, false, false, false),
    /*  85 */ row(4, Some(16), None, false, true, false, false),
    /*  86 */ row(4, Some(16), None, false, true, false, false),
    /*  87 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  88 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  89 */ row(4, Some(32), None, false, true, false, false),
    /*  90 */ row(4, Some(32), Some(32), false, true, true, false),
    /*  91 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  92 */ row(4, Some(32), Some(32), false, true, true, false),
    /*  93 */ row(4, Some(32), Some(32), false, true, false, false),
    /*  94 */ row(4, None, None, false, false, false, false),
    /*  95 */ row(4, None, None, false, false, false, false),
    /*  96 */ row(4, None, None, false, false, false, false),
    /*  97 */ row(4, None, None, false, false, false, false),
    /*  98 */ row(4, None, None, false, false, false, false),
    /*  99 */ row(4, None, None, false, false, false, false),
    /* 100 */ row(4, None, None, false, false, false, false),
    /* 101 */ row(4, None, None, false, false, false, false),
    /* 102 */ row(4, None, None, false, false, false, false),
    /* 103 */ row(4, None, None, false, false, false, false),
    /* 104 */ row(4, None, None, false, false, false, false),
    /* 105 */ row(4, None, None, false, false, false, false),
    /* 106 */ row(4, None, None, false, false, false, false),
    /* 107 */ row(4, None, None, false, false, false, false),
    /* 108 */ row(4, None, None, false, false, false, false),
    /* 109 */ row(4, None, None, false, false, false, false),
    /* 110 */ row(4, None, None, false, false, false, false),
    /* 111 */ row(4, None, None, false, false, false, false),
    /* 112 */ row(4, None, None, false, false, false, false),
    /* 113 */ row(4, None, None, false, false, false, false),
    /* 114 */ row(4, None, None, false, false, false, false),
    /* 115 */ row(4, Some(16), None, false, true, false, false),
];

fn info(format: u32) -> FormatInfo {
    match FORMAT_TABLE.get(format as usize) {
        Some(row) => *row,
        None => DEFAULT_ROW,
    }
}

/// Bytes per pixel of a `DXGI_FORMAT`, for computing the WDDM surface pitch.
pub(crate) fn bytes_per_pixel(format: u32) -> u32 {
    info(format).bytes_per_pixel as u32
}

/// Bits per sample for D3D11 output/MSAA validation.
pub(crate) fn bits_per_sample(format: u32) -> Option<u32> {
    info(format).bits_per_sample.map(u32::from)
}

/// Bits per sample of the format's output family.
pub(crate) fn output_family_bits(format: u32) -> Option<u32> {
    info(format).output_family_bits.map(u32::from)
}

/// Whether the format must be excluded from the MSAA answer regardless of its
/// support bits.
pub(crate) fn msaa_ineligible(format: u32) -> bool {
    info(format).msaa_ineligible
}

pub(crate) fn resolve_required(format: u32) -> bool {
    info(format).resolve_required
}

pub(crate) fn color_typeless_parent(format: u32) -> bool {
    info(format).color_typeless_parent
}

pub(crate) fn integer_typed(format: u32) -> bool {
    info(format).integer_typed
}

// --- The legacy D3DDDIFORMAT bridge ----------------------------------------
//
// A different question from the table above: the KMD's DescribeAllocation
// consumes legacy D3DDDIFORMAT values, not DXGI_FORMAT, and the mapping is
// two-way and lossy in both directions. It is a two-entry correspondence, not
// a per-format classification, so it stays a match rather than a table column.

pub(crate) const D3DDDIFMT_UNKNOWN: u32 = 0;
pub(crate) const D3DDDIFMT_A8R8G8B8: u32 = 21;
pub(crate) const D3DDDIFMT_A8B8G8R8: u32 = 32;
pub(crate) const DXGI_FORMAT_R8G8B8A8_UNORM: u32 = 28;
pub(crate) const DXGI_FORMAT_B8G8R8A8_UNORM: u32 = 87;

/// DXGI -> legacy D3DDDIFORMAT. `D3DDDIFMT_UNKNOWN` for anything else; the
/// caller is expected to say so out loud rather than stamp a silent 0.
pub(crate) fn to_d3dddi(format: u32) -> u32 {
    match format {
        DXGI_FORMAT_R8G8B8A8_UNORM => D3DDDIFMT_A8B8G8R8,
        DXGI_FORMAT_B8G8R8A8_UNORM => D3DDDIFMT_A8R8G8B8,
        _ => D3DDDIFMT_UNKNOWN,
    }
}

/// Legacy D3DDDIFORMAT -> DXGI, as a bare number. Unlike [`to_d3dddi`] this
/// has a total default (BGRA), which is the pre-existing contract: the two
/// legacy values are the only ones any Helios allocation carries.
pub(crate) fn from_d3dddi(format: u32) -> u32 {
    match format {
        D3DDDIFMT_A8R8G8B8 => DXGI_FORMAT_B8G8R8A8_UNORM,
        D3DDDIFMT_A8B8G8R8 => DXGI_FORMAT_R8G8B8A8_UNORM,
        _ => DXGI_FORMAT_B8G8R8A8_UNORM,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // The pre-change predicates, VERBATIM. They are the specification this
    // table is asserted against; do not "tidy" them.

    fn legacy_bytes_per_pixel(format: u32) -> u32 {
        match format {
            1..=4 => 16,  // R32G32B32A32_*
            5..=8 => 12,  // R32G32B32_*
            9..=14 => 8,  // R16G16B16A16_*
            15..=19 => 8, // R32G32_*, R32G8X24 depth
            60..=66 => 1, // R8_TYPELESS/UNORM/UINT/SNORM/SINT, A8_UNORM, R1_UNORM
            _ => 4,
        }
    }

    fn legacy_bits_per_sample(format: u32) -> Option<u32> {
        match format {
            1..=4 => Some(128),        // R32G32B32A32_*
            5..=8 => Some(96),         // R32G32B32_*
            9..=18 => Some(64),        // R16G16B16A16_*, R32G32_*
            19..=22 => Some(64),       // R32G8X24 / D32_FLOAT_S8X24 family
            23..=32 => Some(32),       // R10G10B10A2, R11G11B10, R8G8B8A8
            33..=47 => Some(32),       // R16G16, R32, R24G8
            48..=59 => Some(16),       // R8G8, R16 / D16
            60..=65 => Some(8),        // R8, A8
            85 | 86 | 115 => Some(16), // B5G6R5, B5G5R5A1, B4G4R4A4
            87..=93 => Some(32),       // BGRA/RGBX and XR_BIAS
            _ => None,
        }
    }

    fn legacy_output_family_bits(format: u32) -> Option<u32> {
        match format {
            1..=4 => Some(128),            // R32G32B32A32 family
            5..=8 => Some(96),             // R32G32B32 family
            9..=18 => Some(64),            // R16G16B16A16 / R32G32 families
            19..=22 => Some(64),           // R32G8X24 / D32_FLOAT_S8X24 family
            23..=32 => Some(32),           // R10G10B10A2, R8G8B8A8 families
            33..=47 => Some(32),           // R16G16, R32, R24G8 families
            48..=59 => Some(16),           // R8G8, R16 / D16 families
            60..=64 => Some(8),            // R8 family
            87 | 88 | 90..=93 => Some(32), // BGRA/RGBX families
            _ => None,
        }
    }

    fn legacy_msaa_ineligible(format: u32) -> bool {
        matches!(format, 21 | 22 | 46 | 47)
    }

    fn legacy_resolve_required(format: u32) -> bool {
        match format {
            // FLOAT families.
            2 | 6 | 10 | 16 | 26 | 34 | 41 | 54 => true,
            // UNORM / UNORM_SRGB families.
            11 | 24 | 28 | 29 | 35 | 45 | 46 | 49 | 55 | 56 | 61 | 85 | 86 | 87 | 88 | 89 | 91
            | 93 | 115 => true,
            // SNORM families.
            13 | 31 | 37 | 51 | 58 | 63 => true,
            // Typeless parents whose output views include at least one
            // resolvable UNORM/SNORM/FLOAT interpretation.
            1 | 5 | 9 | 15 | 19 | 23 | 27 | 33 | 39 | 44 | 48 | 53 | 60 | 90 | 92 => true,
            _ => false,
        }
    }

    fn legacy_color_typeless_parent(format: u32) -> bool {
        matches!(
            format,
            1 | 5 | 9 | 15 | 23 | 27 | 33 | 48 | 53 | 60 | 90 | 92
        )
    }

    fn legacy_integer_typed_format(format: u32) -> bool {
        matches!(
            format,
            3 | 4
                | 7
                | 8
                | 12
                | 14
                | 17
                | 18
                | 25
                | 30
                | 32
                | 36
                | 38
                | 42
                | 43
                | 50
                | 52
                | 57
                | 59
                | 62
                | 64
        )
    }

    fn legacy_to_d3dddi(format: u32) -> u32 {
        const DXGI_FORMAT_R8G8B8A8_UNORM: u32 = 28;
        const DXGI_FORMAT_B8G8R8A8_UNORM: u32 = 87;
        const D3DDDIFMT_A8R8G8B8: u32 = 21;
        const D3DDDIFMT_A8B8G8R8: u32 = 32;
        match format {
            DXGI_FORMAT_R8G8B8A8_UNORM => D3DDDIFMT_A8B8G8R8,
            DXGI_FORMAT_B8G8R8A8_UNORM => D3DDDIFMT_A8R8G8B8,
            _ => 0,
        }
    }

    /// R1010's whole proof. Every predicate, every format number the runtime
    /// can hand us, including the out-of-table tail past 115.
    #[test]
    fn table_answers_match_the_pre_change_predicates() {
        for f in 0u32..=200 {
            assert_eq!(bytes_per_pixel(f), legacy_bytes_per_pixel(f), "bpp {f}");
            assert_eq!(bits_per_sample(f), legacy_bits_per_sample(f), "bps {f}");
            assert_eq!(
                output_family_bits(f),
                legacy_output_family_bits(f),
                "family {f}"
            );
            assert_eq!(msaa_ineligible(f), legacy_msaa_ineligible(f), "msaa {f}");
            assert_eq!(
                resolve_required(f),
                legacy_resolve_required(f),
                "resolve {f}"
            );
            assert_eq!(
                color_typeless_parent(f),
                legacy_color_typeless_parent(f),
                "typeless {f}"
            );
            assert_eq!(integer_typed(f), legacy_integer_typed_format(f), "int {f}");
            assert_eq!(to_d3dddi(f), legacy_to_d3dddi(f), "d3dddi {f}");
        }
    }

    /// The three documented `bits_per_sample` / `output_family_bits`
    /// divergences, pinned so a future edit has to acknowledge them.
    #[test]
    fn the_three_family_divergences_are_intentional() {
        for f in [65u32, 85, 86, 89, 115] {
            assert!(bits_per_sample(f).is_some(), "sample bits for {f}");
            assert!(output_family_bits(f).is_none(), "family bits for {f}");
        }
    }

    /// The legacy round trip both ways, including the total BGRA default.
    #[test]
    fn the_legacy_d3dddi_correspondence_round_trips() {
        assert_eq!(to_d3dddi(DXGI_FORMAT_R8G8B8A8_UNORM), D3DDDIFMT_A8B8G8R8);
        assert_eq!(to_d3dddi(DXGI_FORMAT_B8G8R8A8_UNORM), D3DDDIFMT_A8R8G8B8);
        assert_eq!(to_d3dddi(1), D3DDDIFMT_UNKNOWN);
        assert_eq!(from_d3dddi(D3DDDIFMT_A8B8G8R8), DXGI_FORMAT_R8G8B8A8_UNORM);
        assert_eq!(from_d3dddi(D3DDDIFMT_A8R8G8B8), DXGI_FORMAT_B8G8R8A8_UNORM);
        assert_eq!(from_d3dddi(0), DXGI_FORMAT_B8G8R8A8_UNORM);
    }
}
