#!/usr/bin/env python3
"""Generate the D12-G5 spy's slot tables and thunk assembly from the staged SDK header.

Run on the LINUX host, against tmp/dx12/sdk/d3d12umddi.h (SDK 10.0.26100.0):

    python3 tools/d3d12_spy/gen_slots.py

Everything it writes is generated — never hand-edit the outputs. Regenerate whenever the
SDK pin moves: a stale slot list mislabels every line in the log, which is worse than no
log (DDI_REFERENCE.md §15.2).

The counts are asserted here, against DECISIONS.md §4.1's canonical table:
    D3D12DDI_DEVICE_FUNCS_CORE_0109        124
    D3D12DDI_COMMAND_LIST_FUNCS_3D_0108     75
    D3D12DDI_COMMAND_QUEUE_FUNCS_CORE_0001   7
    D3D12DDI_ADAPTERFUNCS_0109               8
    D3D12DDICAPS_TYPE                       43 enumerators (7 deprecated -> 36 live)
    D3D12DDI_TABLE_TYPE                     25 enumerators
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
HDR = os.path.join(ROOT, "tmp", "dx12", "sdk", "d3d12umddi.h")

# The seven `// Deprecated` enumerators, GATES.md §4.6. Kept as data so the generated
# table can carry the flag and answers.md can assert their absence.
DEPRECATED_CAPS = {1000, 1001, 1010, 1058, 1063, 1064, 1065}

# Ring capacity for the ordered call trace, in events. Must match TRACE_CAP in the .asm
# and kTraceCap in the .cpp. 1 Mi events = 4 MiB.
TRACE_CAP = 1 << 20

# Generic DXGI-table thunks. D3D12DDI_TABLE_TYPE_DXGI's struct is not in this header
# (DDI_REFERENCE.md §2.3): the candidates are 21 or 22 members. Generate a few spare so
# the observed TableSize can be covered whichever shape the runtime asks for.
DXGI_SLOTS = 32


def read_header():
    if not os.path.exists(HDR):
        sys.exit(
            "d3d12umddi.h is not staged at %s.\n"
            "Re-stage it with the PowerShell block in DECISIONS.md's preamble." % HDR
        )
    with open(HDR, encoding="utf-8", errors="replace") as f:
        return f.read().split("\n")


MEMBER = re.compile(r"^\s*(?:PFN\w+|void\*|VOID\*)\s+(\w+);")


def struct_members(lines, name):
    """Members of `typedef struct <name>`, in declaration order.

    Only the outer `#if` arms are taken: the members this walk sees are ungated in every
    struct it is used on (verified — the four baseline tables carry no #if/#else, unlike
    D3D12DDI_CORELAYER_DEVICECALLBACKS_*, which is not one of them)."""
    start = None
    for i, l in enumerate(lines):
        if l.startswith("typedef struct " + name):
            start = i
            break
    if start is None:
        sys.exit("struct %s not found in %s" % (name, HDR))
    out = []
    j = start
    while not lines[j].startswith("}"):
        if lines[j].strip().startswith("#"):
            sys.exit(
                "%s contains a preprocessor gate at line %d (%r) — this generator's "
                "flat walk would miscount it." % (name, j + 1, lines[j])
            )
        m = MEMBER.match(lines[j])
        if m:
            out.append(m.group(1))
        j += 1
    return out


ENUMERATOR = re.compile(r"^\s*(D3D12DDI\w+)\s*=\s*(\d+)\s*,")


def enum_values(lines, name):
    """(name, value) pairs of `typedef enum <name>`, skipping commented-out lines."""
    start = None
    for i, l in enumerate(lines):
        if l.startswith("typedef enum " + name):
            start = i
            break
    if start is None:
        sys.exit("enum %s not found in %s" % (name, HDR))
    out = []
    j = start
    while not lines[j].startswith("}"):
        m = ENUMERATOR.match(lines[j])
        if m:
            out.append((m.group(1), int(m.group(2))))
        j += 1
    return out


BANNER = (
    "/* GENERATED by tools/d3d12_spy/gen_slots.py from tmp/dx12/sdk/d3d12umddi.h\n"
    " * (Windows SDK 10.0.26100.0). Do not hand-edit - regenerate. */\n"
)

ASM_BANNER = (
    "; GENERATED by tools/d3d12_spy/gen_slots.py from tmp/dx12/sdk/d3d12umddi.h\n"
    "; (Windows SDK 10.0.26100.0). Do not hand-edit - regenerate.\n"
)


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %-34s %5d lines" % (os.path.basename(path), text.count("\n")))


def emit_slot_inc(path, members):
    body = "".join("X(%d, %s)\n" % (i, m) for i, m in enumerate(members))
    write(path, BANNER + body)


def emit_stub(tag, idx, hits_sym, snap_sym, label):
    """One ABI-transparent forwarder.

    It touches only R10, R11 and the flags — all volatile in the Microsoft x64 ABI and
    none of them an argument register (RCX/RDX/R8/R9 + XMM0-3 pass through untouched) —
    and it uses no stack at all, so the callee sees exactly the RSP, return address and
    shadow space it would have seen on a direct call. That is why the thunk does not need
    the slot's real signature, which §7.3(2) forbids hand-writing anyway.

    The trace ring keeps the FIRST TRACE_CAP events (the gate wants the first frame, not
    the last), while g_spy_trace_idx keeps counting past the cap so the dump can report
    how many were dropped. Per-slot totals come from the separate hit counter, which never
    saturates."""
    code = (tag << 24) | idx
    return (
        "%s PROC\n"
        "    lock inc dword ptr [%s + %d]\n"
        "    mov     r11d, 1\n"
        "    lock xadd dword ptr [g_spy_trace_idx], r11d\n"
        "    cmp     r11d, %08xh\n"
        "    jae     %s_skip\n"
        "    lea     r10, [g_spy_trace]\n"
        "    mov     dword ptr [r10+r11*4], %08xh\n"
        "%s_skip:\n"
        "    jmp     qword ptr [%s + %d]\n"
        "%s ENDP\n\n" % (
            label, hits_sym, idx * 4, TRACE_CAP, label, code, label, snap_sym, idx * 8,
            label,
        )
    )


def main():
    lines = read_header()
    if len(lines) - 1 != 19031:
        print("WARNING: d3d12umddi.h is %d lines, not the 19031-line pin"
              % (len(lines) - 1))

    core = struct_members(lines, "D3D12DDI_DEVICE_FUNCS_CORE_0109")
    cl = struct_members(lines, "D3D12DDI_COMMAND_LIST_FUNCS_3D_0108")
    queue = struct_members(lines, "D3D12DDI_COMMAND_QUEUE_FUNCS_CORE_0001")
    adapter = struct_members(lines, "D3D12DDI_ADAPTERFUNCS_0109")
    caps = enum_values(lines, "D3D12DDICAPS_TYPE")
    tables = enum_values(lines, "D3D12DDI_TABLE_TYPE")

    for got, want, what in (
        (len(core), 124, "DEVICE_FUNCS_CORE_0109"),
        (len(cl), 75, "COMMAND_LIST_FUNCS_3D_0108"),
        (len(queue), 7, "COMMAND_QUEUE_FUNCS_CORE_0001"),
        (len(adapter), 8, "ADAPTERFUNCS_0109"),
        (len(caps), 43, "D3D12DDICAPS_TYPE"),
        (len(tables), 25, "D3D12DDI_TABLE_TYPE"),
    ):
        if got != want:
            sys.exit("%s: got %d, DECISIONS.md §4.1 says %d — resolve before building"
                     % (what, got, want))

    seen_dep = {v for _, v in caps} & DEPRECATED_CAPS
    if seen_dep != DEPRECATED_CAPS:
        sys.exit("deprecated caps set mismatch: header has %s, GATES.md §4.6 lists %s"
                 % (sorted(seen_dep), sorted(DEPRECATED_CAPS)))

    emit_slot_inc(os.path.join(HERE, "slots_core_0109.inc"), core)
    emit_slot_inc(os.path.join(HERE, "slots_cl_0108.inc"), cl)
    emit_slot_inc(os.path.join(HERE, "slots_queue_0001.inc"), queue)
    emit_slot_inc(os.path.join(HERE, "slots_adapter_0109.inc"), adapter)

    write(os.path.join(HERE, "caps_types.inc"),
          BANNER + "".join("CAP(%d, %s, %d)\n" % (v, n, 1 if v in DEPRECATED_CAPS else 0)
                           for n, v in caps))
    write(os.path.join(HERE, "table_types.inc"),
          BANNER + "".join("TBL(%d, %s)\n" % (v, n) for n, v in tables))

    asm = [ASM_BANNER, "\n_TEXT SEGMENT\n\n",
           "EXTERN g_spy_trace:DWORD\n",
           "EXTERN g_spy_trace_idx:DWORD\n"]
    for sym in ("core", "cl", "queue", "dxgi"):
        asm.append("EXTERN g_spy_%s_hits:DWORD\n" % sym)
        asm.append("EXTERN g_spy_%s_snapshot:QWORD\n" % sym)
    asm.append("\n")
    for tag, (kind, members) in enumerate(
            (("core", core), ("cl", cl), ("queue", queue))):
        for i in range(len(members)):
            asm.append(emit_stub(tag, i, "g_spy_%s_hits" % kind,
                                 "g_spy_%s_snapshot" % kind, "spy_%s_%d" % (kind, i)))
    # tag 3 is the DXGI table, whose struct is not in this header (§2.3).
    for i in range(DXGI_SLOTS):
        asm.append(emit_stub(3, i, "g_spy_dxgi_hits", "g_spy_dxgi_snapshot",
                             "spy_dxgi_%d" % i))
    asm.append("_TEXT ENDS\n\nEND\n")
    write(os.path.join(HERE, "spy_thunks.asm"), "".join(asm))

    write(os.path.join(HERE, "slots_dxgi.inc"),
          BANNER + "".join("X(%d, dxgi_slot_%d)\n" % (i, i) for i in range(DXGI_SLOTS)))

    print("core=%d cl=%d queue=%d adapter=%d caps=%d(live %d) tables=%d dxgi_thunks=%d"
          % (len(core), len(cl), len(queue), len(adapter), len(caps),
             len(caps) - len(DEPRECATED_CAPS), len(tables), DXGI_SLOTS))


if __name__ == "__main__":
    main()
