; GENERATED by tools/d3d12_spy/gen_slots.py from tmp/dx12/sdk/d3d12umddi.h
; (Windows SDK 10.0.26100.0). Do not hand-edit - regenerate.

_TEXT SEGMENT

EXTERN g_spy_trace:DWORD
EXTERN g_spy_trace_idx:DWORD
EXTERN g_spy_core_hits:DWORD
EXTERN g_spy_core_snapshot:QWORD
EXTERN g_spy_cl_hits:DWORD
EXTERN g_spy_cl_snapshot:QWORD
EXTERN g_spy_queue_hits:DWORD
EXTERN g_spy_queue_snapshot:QWORD
EXTERN g_spy_dxgi_hits:DWORD
EXTERN g_spy_dxgi_snapshot:QWORD

spy_core_0 PROC
    lock inc dword ptr [g_spy_core_hits + 0]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_0_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000000h
spy_core_0_skip:
    jmp     qword ptr [g_spy_core_snapshot + 0]
spy_core_0 ENDP

spy_core_1 PROC
    lock inc dword ptr [g_spy_core_hits + 4]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_1_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000001h
spy_core_1_skip:
    jmp     qword ptr [g_spy_core_snapshot + 8]
spy_core_1 ENDP

spy_core_2 PROC
    lock inc dword ptr [g_spy_core_hits + 8]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_2_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000002h
spy_core_2_skip:
    jmp     qword ptr [g_spy_core_snapshot + 16]
spy_core_2 ENDP

spy_core_3 PROC
    lock inc dword ptr [g_spy_core_hits + 12]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_3_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000003h
spy_core_3_skip:
    jmp     qword ptr [g_spy_core_snapshot + 24]
spy_core_3 ENDP

spy_core_4 PROC
    lock inc dword ptr [g_spy_core_hits + 16]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_4_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000004h
spy_core_4_skip:
    jmp     qword ptr [g_spy_core_snapshot + 32]
spy_core_4 ENDP

spy_core_5 PROC
    lock inc dword ptr [g_spy_core_hits + 20]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_5_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000005h
spy_core_5_skip:
    jmp     qword ptr [g_spy_core_snapshot + 40]
spy_core_5 ENDP

spy_core_6 PROC
    lock inc dword ptr [g_spy_core_hits + 24]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_6_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000006h
spy_core_6_skip:
    jmp     qword ptr [g_spy_core_snapshot + 48]
spy_core_6 ENDP

spy_core_7 PROC
    lock inc dword ptr [g_spy_core_hits + 28]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_7_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000007h
spy_core_7_skip:
    jmp     qword ptr [g_spy_core_snapshot + 56]
spy_core_7 ENDP

spy_core_8 PROC
    lock inc dword ptr [g_spy_core_hits + 32]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_8_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000008h
spy_core_8_skip:
    jmp     qword ptr [g_spy_core_snapshot + 64]
spy_core_8 ENDP

spy_core_9 PROC
    lock inc dword ptr [g_spy_core_hits + 36]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_9_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000009h
spy_core_9_skip:
    jmp     qword ptr [g_spy_core_snapshot + 72]
spy_core_9 ENDP

spy_core_10 PROC
    lock inc dword ptr [g_spy_core_hits + 40]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_10_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000000ah
spy_core_10_skip:
    jmp     qword ptr [g_spy_core_snapshot + 80]
spy_core_10 ENDP

spy_core_11 PROC
    lock inc dword ptr [g_spy_core_hits + 44]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_11_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000000bh
spy_core_11_skip:
    jmp     qword ptr [g_spy_core_snapshot + 88]
spy_core_11 ENDP

spy_core_12 PROC
    lock inc dword ptr [g_spy_core_hits + 48]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_12_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000000ch
spy_core_12_skip:
    jmp     qword ptr [g_spy_core_snapshot + 96]
spy_core_12 ENDP

spy_core_13 PROC
    lock inc dword ptr [g_spy_core_hits + 52]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_13_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000000dh
spy_core_13_skip:
    jmp     qword ptr [g_spy_core_snapshot + 104]
spy_core_13 ENDP

spy_core_14 PROC
    lock inc dword ptr [g_spy_core_hits + 56]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_14_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000000eh
spy_core_14_skip:
    jmp     qword ptr [g_spy_core_snapshot + 112]
spy_core_14 ENDP

spy_core_15 PROC
    lock inc dword ptr [g_spy_core_hits + 60]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_15_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000000fh
spy_core_15_skip:
    jmp     qword ptr [g_spy_core_snapshot + 120]
spy_core_15 ENDP

spy_core_16 PROC
    lock inc dword ptr [g_spy_core_hits + 64]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_16_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000010h
spy_core_16_skip:
    jmp     qword ptr [g_spy_core_snapshot + 128]
spy_core_16 ENDP

spy_core_17 PROC
    lock inc dword ptr [g_spy_core_hits + 68]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_17_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000011h
spy_core_17_skip:
    jmp     qword ptr [g_spy_core_snapshot + 136]
spy_core_17 ENDP

spy_core_18 PROC
    lock inc dword ptr [g_spy_core_hits + 72]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_18_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000012h
spy_core_18_skip:
    jmp     qword ptr [g_spy_core_snapshot + 144]
spy_core_18 ENDP

spy_core_19 PROC
    lock inc dword ptr [g_spy_core_hits + 76]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_19_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000013h
spy_core_19_skip:
    jmp     qword ptr [g_spy_core_snapshot + 152]
spy_core_19 ENDP

spy_core_20 PROC
    lock inc dword ptr [g_spy_core_hits + 80]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_20_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000014h
spy_core_20_skip:
    jmp     qword ptr [g_spy_core_snapshot + 160]
spy_core_20 ENDP

spy_core_21 PROC
    lock inc dword ptr [g_spy_core_hits + 84]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_21_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000015h
spy_core_21_skip:
    jmp     qword ptr [g_spy_core_snapshot + 168]
spy_core_21 ENDP

spy_core_22 PROC
    lock inc dword ptr [g_spy_core_hits + 88]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_22_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000016h
spy_core_22_skip:
    jmp     qword ptr [g_spy_core_snapshot + 176]
spy_core_22 ENDP

spy_core_23 PROC
    lock inc dword ptr [g_spy_core_hits + 92]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_23_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000017h
spy_core_23_skip:
    jmp     qword ptr [g_spy_core_snapshot + 184]
spy_core_23 ENDP

spy_core_24 PROC
    lock inc dword ptr [g_spy_core_hits + 96]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_24_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000018h
spy_core_24_skip:
    jmp     qword ptr [g_spy_core_snapshot + 192]
spy_core_24 ENDP

spy_core_25 PROC
    lock inc dword ptr [g_spy_core_hits + 100]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_25_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000019h
spy_core_25_skip:
    jmp     qword ptr [g_spy_core_snapshot + 200]
spy_core_25 ENDP

spy_core_26 PROC
    lock inc dword ptr [g_spy_core_hits + 104]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_26_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000001ah
spy_core_26_skip:
    jmp     qword ptr [g_spy_core_snapshot + 208]
spy_core_26 ENDP

spy_core_27 PROC
    lock inc dword ptr [g_spy_core_hits + 108]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_27_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000001bh
spy_core_27_skip:
    jmp     qword ptr [g_spy_core_snapshot + 216]
spy_core_27 ENDP

spy_core_28 PROC
    lock inc dword ptr [g_spy_core_hits + 112]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_28_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000001ch
spy_core_28_skip:
    jmp     qword ptr [g_spy_core_snapshot + 224]
spy_core_28 ENDP

spy_core_29 PROC
    lock inc dword ptr [g_spy_core_hits + 116]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_29_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000001dh
spy_core_29_skip:
    jmp     qword ptr [g_spy_core_snapshot + 232]
spy_core_29 ENDP

spy_core_30 PROC
    lock inc dword ptr [g_spy_core_hits + 120]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_30_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000001eh
spy_core_30_skip:
    jmp     qword ptr [g_spy_core_snapshot + 240]
spy_core_30 ENDP

spy_core_31 PROC
    lock inc dword ptr [g_spy_core_hits + 124]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_31_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000001fh
spy_core_31_skip:
    jmp     qword ptr [g_spy_core_snapshot + 248]
spy_core_31 ENDP

spy_core_32 PROC
    lock inc dword ptr [g_spy_core_hits + 128]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_32_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000020h
spy_core_32_skip:
    jmp     qword ptr [g_spy_core_snapshot + 256]
spy_core_32 ENDP

spy_core_33 PROC
    lock inc dword ptr [g_spy_core_hits + 132]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_33_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000021h
spy_core_33_skip:
    jmp     qword ptr [g_spy_core_snapshot + 264]
spy_core_33 ENDP

spy_core_34 PROC
    lock inc dword ptr [g_spy_core_hits + 136]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_34_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000022h
spy_core_34_skip:
    jmp     qword ptr [g_spy_core_snapshot + 272]
spy_core_34 ENDP

spy_core_35 PROC
    lock inc dword ptr [g_spy_core_hits + 140]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_35_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000023h
spy_core_35_skip:
    jmp     qword ptr [g_spy_core_snapshot + 280]
spy_core_35 ENDP

spy_core_36 PROC
    lock inc dword ptr [g_spy_core_hits + 144]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_36_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000024h
spy_core_36_skip:
    jmp     qword ptr [g_spy_core_snapshot + 288]
spy_core_36 ENDP

spy_core_37 PROC
    lock inc dword ptr [g_spy_core_hits + 148]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_37_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000025h
spy_core_37_skip:
    jmp     qword ptr [g_spy_core_snapshot + 296]
spy_core_37 ENDP

spy_core_38 PROC
    lock inc dword ptr [g_spy_core_hits + 152]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_38_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000026h
spy_core_38_skip:
    jmp     qword ptr [g_spy_core_snapshot + 304]
spy_core_38 ENDP

spy_core_39 PROC
    lock inc dword ptr [g_spy_core_hits + 156]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_39_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000027h
spy_core_39_skip:
    jmp     qword ptr [g_spy_core_snapshot + 312]
spy_core_39 ENDP

spy_core_40 PROC
    lock inc dword ptr [g_spy_core_hits + 160]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_40_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000028h
spy_core_40_skip:
    jmp     qword ptr [g_spy_core_snapshot + 320]
spy_core_40 ENDP

spy_core_41 PROC
    lock inc dword ptr [g_spy_core_hits + 164]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_41_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000029h
spy_core_41_skip:
    jmp     qword ptr [g_spy_core_snapshot + 328]
spy_core_41 ENDP

spy_core_42 PROC
    lock inc dword ptr [g_spy_core_hits + 168]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_42_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000002ah
spy_core_42_skip:
    jmp     qword ptr [g_spy_core_snapshot + 336]
spy_core_42 ENDP

spy_core_43 PROC
    lock inc dword ptr [g_spy_core_hits + 172]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_43_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000002bh
spy_core_43_skip:
    jmp     qword ptr [g_spy_core_snapshot + 344]
spy_core_43 ENDP

spy_core_44 PROC
    lock inc dword ptr [g_spy_core_hits + 176]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_44_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000002ch
spy_core_44_skip:
    jmp     qword ptr [g_spy_core_snapshot + 352]
spy_core_44 ENDP

spy_core_45 PROC
    lock inc dword ptr [g_spy_core_hits + 180]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_45_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000002dh
spy_core_45_skip:
    jmp     qword ptr [g_spy_core_snapshot + 360]
spy_core_45 ENDP

spy_core_46 PROC
    lock inc dword ptr [g_spy_core_hits + 184]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_46_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000002eh
spy_core_46_skip:
    jmp     qword ptr [g_spy_core_snapshot + 368]
spy_core_46 ENDP

spy_core_47 PROC
    lock inc dword ptr [g_spy_core_hits + 188]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_47_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000002fh
spy_core_47_skip:
    jmp     qword ptr [g_spy_core_snapshot + 376]
spy_core_47 ENDP

spy_core_48 PROC
    lock inc dword ptr [g_spy_core_hits + 192]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_48_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000030h
spy_core_48_skip:
    jmp     qword ptr [g_spy_core_snapshot + 384]
spy_core_48 ENDP

spy_core_49 PROC
    lock inc dword ptr [g_spy_core_hits + 196]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_49_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000031h
spy_core_49_skip:
    jmp     qword ptr [g_spy_core_snapshot + 392]
spy_core_49 ENDP

spy_core_50 PROC
    lock inc dword ptr [g_spy_core_hits + 200]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_50_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000032h
spy_core_50_skip:
    jmp     qword ptr [g_spy_core_snapshot + 400]
spy_core_50 ENDP

spy_core_51 PROC
    lock inc dword ptr [g_spy_core_hits + 204]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_51_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000033h
spy_core_51_skip:
    jmp     qword ptr [g_spy_core_snapshot + 408]
spy_core_51 ENDP

spy_core_52 PROC
    lock inc dword ptr [g_spy_core_hits + 208]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_52_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000034h
spy_core_52_skip:
    jmp     qword ptr [g_spy_core_snapshot + 416]
spy_core_52 ENDP

spy_core_53 PROC
    lock inc dword ptr [g_spy_core_hits + 212]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_53_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000035h
spy_core_53_skip:
    jmp     qword ptr [g_spy_core_snapshot + 424]
spy_core_53 ENDP

spy_core_54 PROC
    lock inc dword ptr [g_spy_core_hits + 216]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_54_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000036h
spy_core_54_skip:
    jmp     qword ptr [g_spy_core_snapshot + 432]
spy_core_54 ENDP

spy_core_55 PROC
    lock inc dword ptr [g_spy_core_hits + 220]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_55_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000037h
spy_core_55_skip:
    jmp     qword ptr [g_spy_core_snapshot + 440]
spy_core_55 ENDP

spy_core_56 PROC
    lock inc dword ptr [g_spy_core_hits + 224]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_56_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000038h
spy_core_56_skip:
    jmp     qword ptr [g_spy_core_snapshot + 448]
spy_core_56 ENDP

spy_core_57 PROC
    lock inc dword ptr [g_spy_core_hits + 228]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_57_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000039h
spy_core_57_skip:
    jmp     qword ptr [g_spy_core_snapshot + 456]
spy_core_57 ENDP

spy_core_58 PROC
    lock inc dword ptr [g_spy_core_hits + 232]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_58_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000003ah
spy_core_58_skip:
    jmp     qword ptr [g_spy_core_snapshot + 464]
spy_core_58 ENDP

spy_core_59 PROC
    lock inc dword ptr [g_spy_core_hits + 236]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_59_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000003bh
spy_core_59_skip:
    jmp     qword ptr [g_spy_core_snapshot + 472]
spy_core_59 ENDP

spy_core_60 PROC
    lock inc dword ptr [g_spy_core_hits + 240]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_60_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000003ch
spy_core_60_skip:
    jmp     qword ptr [g_spy_core_snapshot + 480]
spy_core_60 ENDP

spy_core_61 PROC
    lock inc dword ptr [g_spy_core_hits + 244]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_61_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000003dh
spy_core_61_skip:
    jmp     qword ptr [g_spy_core_snapshot + 488]
spy_core_61 ENDP

spy_core_62 PROC
    lock inc dword ptr [g_spy_core_hits + 248]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_62_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000003eh
spy_core_62_skip:
    jmp     qword ptr [g_spy_core_snapshot + 496]
spy_core_62 ENDP

spy_core_63 PROC
    lock inc dword ptr [g_spy_core_hits + 252]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_63_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000003fh
spy_core_63_skip:
    jmp     qword ptr [g_spy_core_snapshot + 504]
spy_core_63 ENDP

spy_core_64 PROC
    lock inc dword ptr [g_spy_core_hits + 256]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_64_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000040h
spy_core_64_skip:
    jmp     qword ptr [g_spy_core_snapshot + 512]
spy_core_64 ENDP

spy_core_65 PROC
    lock inc dword ptr [g_spy_core_hits + 260]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_65_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000041h
spy_core_65_skip:
    jmp     qword ptr [g_spy_core_snapshot + 520]
spy_core_65 ENDP

spy_core_66 PROC
    lock inc dword ptr [g_spy_core_hits + 264]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_66_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000042h
spy_core_66_skip:
    jmp     qword ptr [g_spy_core_snapshot + 528]
spy_core_66 ENDP

spy_core_67 PROC
    lock inc dword ptr [g_spy_core_hits + 268]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_67_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000043h
spy_core_67_skip:
    jmp     qword ptr [g_spy_core_snapshot + 536]
spy_core_67 ENDP

spy_core_68 PROC
    lock inc dword ptr [g_spy_core_hits + 272]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_68_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000044h
spy_core_68_skip:
    jmp     qword ptr [g_spy_core_snapshot + 544]
spy_core_68 ENDP

spy_core_69 PROC
    lock inc dword ptr [g_spy_core_hits + 276]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_69_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000045h
spy_core_69_skip:
    jmp     qword ptr [g_spy_core_snapshot + 552]
spy_core_69 ENDP

spy_core_70 PROC
    lock inc dword ptr [g_spy_core_hits + 280]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_70_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000046h
spy_core_70_skip:
    jmp     qword ptr [g_spy_core_snapshot + 560]
spy_core_70 ENDP

spy_core_71 PROC
    lock inc dword ptr [g_spy_core_hits + 284]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_71_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000047h
spy_core_71_skip:
    jmp     qword ptr [g_spy_core_snapshot + 568]
spy_core_71 ENDP

spy_core_72 PROC
    lock inc dword ptr [g_spy_core_hits + 288]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_72_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000048h
spy_core_72_skip:
    jmp     qword ptr [g_spy_core_snapshot + 576]
spy_core_72 ENDP

spy_core_73 PROC
    lock inc dword ptr [g_spy_core_hits + 292]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_73_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000049h
spy_core_73_skip:
    jmp     qword ptr [g_spy_core_snapshot + 584]
spy_core_73 ENDP

spy_core_74 PROC
    lock inc dword ptr [g_spy_core_hits + 296]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_74_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000004ah
spy_core_74_skip:
    jmp     qword ptr [g_spy_core_snapshot + 592]
spy_core_74 ENDP

spy_core_75 PROC
    lock inc dword ptr [g_spy_core_hits + 300]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_75_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000004bh
spy_core_75_skip:
    jmp     qword ptr [g_spy_core_snapshot + 600]
spy_core_75 ENDP

spy_core_76 PROC
    lock inc dword ptr [g_spy_core_hits + 304]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_76_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000004ch
spy_core_76_skip:
    jmp     qword ptr [g_spy_core_snapshot + 608]
spy_core_76 ENDP

spy_core_77 PROC
    lock inc dword ptr [g_spy_core_hits + 308]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_77_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000004dh
spy_core_77_skip:
    jmp     qword ptr [g_spy_core_snapshot + 616]
spy_core_77 ENDP

spy_core_78 PROC
    lock inc dword ptr [g_spy_core_hits + 312]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_78_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000004eh
spy_core_78_skip:
    jmp     qword ptr [g_spy_core_snapshot + 624]
spy_core_78 ENDP

spy_core_79 PROC
    lock inc dword ptr [g_spy_core_hits + 316]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_79_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000004fh
spy_core_79_skip:
    jmp     qword ptr [g_spy_core_snapshot + 632]
spy_core_79 ENDP

spy_core_80 PROC
    lock inc dword ptr [g_spy_core_hits + 320]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_80_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000050h
spy_core_80_skip:
    jmp     qword ptr [g_spy_core_snapshot + 640]
spy_core_80 ENDP

spy_core_81 PROC
    lock inc dword ptr [g_spy_core_hits + 324]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_81_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000051h
spy_core_81_skip:
    jmp     qword ptr [g_spy_core_snapshot + 648]
spy_core_81 ENDP

spy_core_82 PROC
    lock inc dword ptr [g_spy_core_hits + 328]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_82_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000052h
spy_core_82_skip:
    jmp     qword ptr [g_spy_core_snapshot + 656]
spy_core_82 ENDP

spy_core_83 PROC
    lock inc dword ptr [g_spy_core_hits + 332]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_83_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000053h
spy_core_83_skip:
    jmp     qword ptr [g_spy_core_snapshot + 664]
spy_core_83 ENDP

spy_core_84 PROC
    lock inc dword ptr [g_spy_core_hits + 336]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_84_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000054h
spy_core_84_skip:
    jmp     qword ptr [g_spy_core_snapshot + 672]
spy_core_84 ENDP

spy_core_85 PROC
    lock inc dword ptr [g_spy_core_hits + 340]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_85_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000055h
spy_core_85_skip:
    jmp     qword ptr [g_spy_core_snapshot + 680]
spy_core_85 ENDP

spy_core_86 PROC
    lock inc dword ptr [g_spy_core_hits + 344]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_86_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000056h
spy_core_86_skip:
    jmp     qword ptr [g_spy_core_snapshot + 688]
spy_core_86 ENDP

spy_core_87 PROC
    lock inc dword ptr [g_spy_core_hits + 348]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_87_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000057h
spy_core_87_skip:
    jmp     qword ptr [g_spy_core_snapshot + 696]
spy_core_87 ENDP

spy_core_88 PROC
    lock inc dword ptr [g_spy_core_hits + 352]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_88_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000058h
spy_core_88_skip:
    jmp     qword ptr [g_spy_core_snapshot + 704]
spy_core_88 ENDP

spy_core_89 PROC
    lock inc dword ptr [g_spy_core_hits + 356]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_89_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000059h
spy_core_89_skip:
    jmp     qword ptr [g_spy_core_snapshot + 712]
spy_core_89 ENDP

spy_core_90 PROC
    lock inc dword ptr [g_spy_core_hits + 360]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_90_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000005ah
spy_core_90_skip:
    jmp     qword ptr [g_spy_core_snapshot + 720]
spy_core_90 ENDP

spy_core_91 PROC
    lock inc dword ptr [g_spy_core_hits + 364]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_91_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000005bh
spy_core_91_skip:
    jmp     qword ptr [g_spy_core_snapshot + 728]
spy_core_91 ENDP

spy_core_92 PROC
    lock inc dword ptr [g_spy_core_hits + 368]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_92_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000005ch
spy_core_92_skip:
    jmp     qword ptr [g_spy_core_snapshot + 736]
spy_core_92 ENDP

spy_core_93 PROC
    lock inc dword ptr [g_spy_core_hits + 372]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_93_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000005dh
spy_core_93_skip:
    jmp     qword ptr [g_spy_core_snapshot + 744]
spy_core_93 ENDP

spy_core_94 PROC
    lock inc dword ptr [g_spy_core_hits + 376]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_94_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000005eh
spy_core_94_skip:
    jmp     qword ptr [g_spy_core_snapshot + 752]
spy_core_94 ENDP

spy_core_95 PROC
    lock inc dword ptr [g_spy_core_hits + 380]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_95_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000005fh
spy_core_95_skip:
    jmp     qword ptr [g_spy_core_snapshot + 760]
spy_core_95 ENDP

spy_core_96 PROC
    lock inc dword ptr [g_spy_core_hits + 384]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_96_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000060h
spy_core_96_skip:
    jmp     qword ptr [g_spy_core_snapshot + 768]
spy_core_96 ENDP

spy_core_97 PROC
    lock inc dword ptr [g_spy_core_hits + 388]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_97_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000061h
spy_core_97_skip:
    jmp     qword ptr [g_spy_core_snapshot + 776]
spy_core_97 ENDP

spy_core_98 PROC
    lock inc dword ptr [g_spy_core_hits + 392]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_98_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000062h
spy_core_98_skip:
    jmp     qword ptr [g_spy_core_snapshot + 784]
spy_core_98 ENDP

spy_core_99 PROC
    lock inc dword ptr [g_spy_core_hits + 396]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_99_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000063h
spy_core_99_skip:
    jmp     qword ptr [g_spy_core_snapshot + 792]
spy_core_99 ENDP

spy_core_100 PROC
    lock inc dword ptr [g_spy_core_hits + 400]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_100_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000064h
spy_core_100_skip:
    jmp     qword ptr [g_spy_core_snapshot + 800]
spy_core_100 ENDP

spy_core_101 PROC
    lock inc dword ptr [g_spy_core_hits + 404]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_101_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000065h
spy_core_101_skip:
    jmp     qword ptr [g_spy_core_snapshot + 808]
spy_core_101 ENDP

spy_core_102 PROC
    lock inc dword ptr [g_spy_core_hits + 408]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_102_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000066h
spy_core_102_skip:
    jmp     qword ptr [g_spy_core_snapshot + 816]
spy_core_102 ENDP

spy_core_103 PROC
    lock inc dword ptr [g_spy_core_hits + 412]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_103_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000067h
spy_core_103_skip:
    jmp     qword ptr [g_spy_core_snapshot + 824]
spy_core_103 ENDP

spy_core_104 PROC
    lock inc dword ptr [g_spy_core_hits + 416]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_104_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000068h
spy_core_104_skip:
    jmp     qword ptr [g_spy_core_snapshot + 832]
spy_core_104 ENDP

spy_core_105 PROC
    lock inc dword ptr [g_spy_core_hits + 420]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_105_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000069h
spy_core_105_skip:
    jmp     qword ptr [g_spy_core_snapshot + 840]
spy_core_105 ENDP

spy_core_106 PROC
    lock inc dword ptr [g_spy_core_hits + 424]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_106_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000006ah
spy_core_106_skip:
    jmp     qword ptr [g_spy_core_snapshot + 848]
spy_core_106 ENDP

spy_core_107 PROC
    lock inc dword ptr [g_spy_core_hits + 428]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_107_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000006bh
spy_core_107_skip:
    jmp     qword ptr [g_spy_core_snapshot + 856]
spy_core_107 ENDP

spy_core_108 PROC
    lock inc dword ptr [g_spy_core_hits + 432]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_108_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000006ch
spy_core_108_skip:
    jmp     qword ptr [g_spy_core_snapshot + 864]
spy_core_108 ENDP

spy_core_109 PROC
    lock inc dword ptr [g_spy_core_hits + 436]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_109_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000006dh
spy_core_109_skip:
    jmp     qword ptr [g_spy_core_snapshot + 872]
spy_core_109 ENDP

spy_core_110 PROC
    lock inc dword ptr [g_spy_core_hits + 440]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_110_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000006eh
spy_core_110_skip:
    jmp     qword ptr [g_spy_core_snapshot + 880]
spy_core_110 ENDP

spy_core_111 PROC
    lock inc dword ptr [g_spy_core_hits + 444]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_111_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000006fh
spy_core_111_skip:
    jmp     qword ptr [g_spy_core_snapshot + 888]
spy_core_111 ENDP

spy_core_112 PROC
    lock inc dword ptr [g_spy_core_hits + 448]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_112_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000070h
spy_core_112_skip:
    jmp     qword ptr [g_spy_core_snapshot + 896]
spy_core_112 ENDP

spy_core_113 PROC
    lock inc dword ptr [g_spy_core_hits + 452]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_113_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000071h
spy_core_113_skip:
    jmp     qword ptr [g_spy_core_snapshot + 904]
spy_core_113 ENDP

spy_core_114 PROC
    lock inc dword ptr [g_spy_core_hits + 456]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_114_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000072h
spy_core_114_skip:
    jmp     qword ptr [g_spy_core_snapshot + 912]
spy_core_114 ENDP

spy_core_115 PROC
    lock inc dword ptr [g_spy_core_hits + 460]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_115_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000073h
spy_core_115_skip:
    jmp     qword ptr [g_spy_core_snapshot + 920]
spy_core_115 ENDP

spy_core_116 PROC
    lock inc dword ptr [g_spy_core_hits + 464]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_116_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000074h
spy_core_116_skip:
    jmp     qword ptr [g_spy_core_snapshot + 928]
spy_core_116 ENDP

spy_core_117 PROC
    lock inc dword ptr [g_spy_core_hits + 468]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_117_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000075h
spy_core_117_skip:
    jmp     qword ptr [g_spy_core_snapshot + 936]
spy_core_117 ENDP

spy_core_118 PROC
    lock inc dword ptr [g_spy_core_hits + 472]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_118_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000076h
spy_core_118_skip:
    jmp     qword ptr [g_spy_core_snapshot + 944]
spy_core_118 ENDP

spy_core_119 PROC
    lock inc dword ptr [g_spy_core_hits + 476]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_119_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000077h
spy_core_119_skip:
    jmp     qword ptr [g_spy_core_snapshot + 952]
spy_core_119 ENDP

spy_core_120 PROC
    lock inc dword ptr [g_spy_core_hits + 480]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_120_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000078h
spy_core_120_skip:
    jmp     qword ptr [g_spy_core_snapshot + 960]
spy_core_120 ENDP

spy_core_121 PROC
    lock inc dword ptr [g_spy_core_hits + 484]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_121_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 00000079h
spy_core_121_skip:
    jmp     qword ptr [g_spy_core_snapshot + 968]
spy_core_121 ENDP

spy_core_122 PROC
    lock inc dword ptr [g_spy_core_hits + 488]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_122_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000007ah
spy_core_122_skip:
    jmp     qword ptr [g_spy_core_snapshot + 976]
spy_core_122 ENDP

spy_core_123 PROC
    lock inc dword ptr [g_spy_core_hits + 492]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_core_123_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0000007bh
spy_core_123_skip:
    jmp     qword ptr [g_spy_core_snapshot + 984]
spy_core_123 ENDP

spy_cl_0 PROC
    lock inc dword ptr [g_spy_cl_hits + 0]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_0_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000000h
spy_cl_0_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 0]
spy_cl_0 ENDP

spy_cl_1 PROC
    lock inc dword ptr [g_spy_cl_hits + 4]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_1_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000001h
spy_cl_1_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 8]
spy_cl_1 ENDP

spy_cl_2 PROC
    lock inc dword ptr [g_spy_cl_hits + 8]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_2_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000002h
spy_cl_2_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 16]
spy_cl_2 ENDP

spy_cl_3 PROC
    lock inc dword ptr [g_spy_cl_hits + 12]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_3_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000003h
spy_cl_3_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 24]
spy_cl_3 ENDP

spy_cl_4 PROC
    lock inc dword ptr [g_spy_cl_hits + 16]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_4_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000004h
spy_cl_4_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 32]
spy_cl_4 ENDP

spy_cl_5 PROC
    lock inc dword ptr [g_spy_cl_hits + 20]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_5_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000005h
spy_cl_5_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 40]
spy_cl_5 ENDP

spy_cl_6 PROC
    lock inc dword ptr [g_spy_cl_hits + 24]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_6_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000006h
spy_cl_6_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 48]
spy_cl_6 ENDP

spy_cl_7 PROC
    lock inc dword ptr [g_spy_cl_hits + 28]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_7_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000007h
spy_cl_7_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 56]
spy_cl_7 ENDP

spy_cl_8 PROC
    lock inc dword ptr [g_spy_cl_hits + 32]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_8_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000008h
spy_cl_8_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 64]
spy_cl_8 ENDP

spy_cl_9 PROC
    lock inc dword ptr [g_spy_cl_hits + 36]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_9_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000009h
spy_cl_9_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 72]
spy_cl_9 ENDP

spy_cl_10 PROC
    lock inc dword ptr [g_spy_cl_hits + 40]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_10_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100000ah
spy_cl_10_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 80]
spy_cl_10 ENDP

spy_cl_11 PROC
    lock inc dword ptr [g_spy_cl_hits + 44]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_11_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100000bh
spy_cl_11_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 88]
spy_cl_11 ENDP

spy_cl_12 PROC
    lock inc dword ptr [g_spy_cl_hits + 48]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_12_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100000ch
spy_cl_12_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 96]
spy_cl_12 ENDP

spy_cl_13 PROC
    lock inc dword ptr [g_spy_cl_hits + 52]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_13_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100000dh
spy_cl_13_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 104]
spy_cl_13 ENDP

spy_cl_14 PROC
    lock inc dword ptr [g_spy_cl_hits + 56]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_14_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100000eh
spy_cl_14_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 112]
spy_cl_14 ENDP

spy_cl_15 PROC
    lock inc dword ptr [g_spy_cl_hits + 60]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_15_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100000fh
spy_cl_15_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 120]
spy_cl_15 ENDP

spy_cl_16 PROC
    lock inc dword ptr [g_spy_cl_hits + 64]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_16_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000010h
spy_cl_16_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 128]
spy_cl_16 ENDP

spy_cl_17 PROC
    lock inc dword ptr [g_spy_cl_hits + 68]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_17_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000011h
spy_cl_17_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 136]
spy_cl_17 ENDP

spy_cl_18 PROC
    lock inc dword ptr [g_spy_cl_hits + 72]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_18_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000012h
spy_cl_18_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 144]
spy_cl_18 ENDP

spy_cl_19 PROC
    lock inc dword ptr [g_spy_cl_hits + 76]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_19_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000013h
spy_cl_19_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 152]
spy_cl_19 ENDP

spy_cl_20 PROC
    lock inc dword ptr [g_spy_cl_hits + 80]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_20_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000014h
spy_cl_20_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 160]
spy_cl_20 ENDP

spy_cl_21 PROC
    lock inc dword ptr [g_spy_cl_hits + 84]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_21_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000015h
spy_cl_21_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 168]
spy_cl_21 ENDP

spy_cl_22 PROC
    lock inc dword ptr [g_spy_cl_hits + 88]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_22_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000016h
spy_cl_22_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 176]
spy_cl_22 ENDP

spy_cl_23 PROC
    lock inc dword ptr [g_spy_cl_hits + 92]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_23_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000017h
spy_cl_23_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 184]
spy_cl_23 ENDP

spy_cl_24 PROC
    lock inc dword ptr [g_spy_cl_hits + 96]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_24_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000018h
spy_cl_24_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 192]
spy_cl_24 ENDP

spy_cl_25 PROC
    lock inc dword ptr [g_spy_cl_hits + 100]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_25_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000019h
spy_cl_25_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 200]
spy_cl_25 ENDP

spy_cl_26 PROC
    lock inc dword ptr [g_spy_cl_hits + 104]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_26_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100001ah
spy_cl_26_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 208]
spy_cl_26 ENDP

spy_cl_27 PROC
    lock inc dword ptr [g_spy_cl_hits + 108]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_27_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100001bh
spy_cl_27_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 216]
spy_cl_27 ENDP

spy_cl_28 PROC
    lock inc dword ptr [g_spy_cl_hits + 112]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_28_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100001ch
spy_cl_28_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 224]
spy_cl_28 ENDP

spy_cl_29 PROC
    lock inc dword ptr [g_spy_cl_hits + 116]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_29_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100001dh
spy_cl_29_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 232]
spy_cl_29 ENDP

spy_cl_30 PROC
    lock inc dword ptr [g_spy_cl_hits + 120]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_30_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100001eh
spy_cl_30_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 240]
spy_cl_30 ENDP

spy_cl_31 PROC
    lock inc dword ptr [g_spy_cl_hits + 124]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_31_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100001fh
spy_cl_31_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 248]
spy_cl_31 ENDP

spy_cl_32 PROC
    lock inc dword ptr [g_spy_cl_hits + 128]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_32_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000020h
spy_cl_32_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 256]
spy_cl_32 ENDP

spy_cl_33 PROC
    lock inc dword ptr [g_spy_cl_hits + 132]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_33_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000021h
spy_cl_33_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 264]
spy_cl_33 ENDP

spy_cl_34 PROC
    lock inc dword ptr [g_spy_cl_hits + 136]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_34_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000022h
spy_cl_34_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 272]
spy_cl_34 ENDP

spy_cl_35 PROC
    lock inc dword ptr [g_spy_cl_hits + 140]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_35_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000023h
spy_cl_35_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 280]
spy_cl_35 ENDP

spy_cl_36 PROC
    lock inc dword ptr [g_spy_cl_hits + 144]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_36_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000024h
spy_cl_36_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 288]
spy_cl_36 ENDP

spy_cl_37 PROC
    lock inc dword ptr [g_spy_cl_hits + 148]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_37_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000025h
spy_cl_37_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 296]
spy_cl_37 ENDP

spy_cl_38 PROC
    lock inc dword ptr [g_spy_cl_hits + 152]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_38_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000026h
spy_cl_38_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 304]
spy_cl_38 ENDP

spy_cl_39 PROC
    lock inc dword ptr [g_spy_cl_hits + 156]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_39_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000027h
spy_cl_39_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 312]
spy_cl_39 ENDP

spy_cl_40 PROC
    lock inc dword ptr [g_spy_cl_hits + 160]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_40_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000028h
spy_cl_40_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 320]
spy_cl_40 ENDP

spy_cl_41 PROC
    lock inc dword ptr [g_spy_cl_hits + 164]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_41_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000029h
spy_cl_41_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 328]
spy_cl_41 ENDP

spy_cl_42 PROC
    lock inc dword ptr [g_spy_cl_hits + 168]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_42_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100002ah
spy_cl_42_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 336]
spy_cl_42 ENDP

spy_cl_43 PROC
    lock inc dword ptr [g_spy_cl_hits + 172]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_43_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100002bh
spy_cl_43_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 344]
spy_cl_43 ENDP

spy_cl_44 PROC
    lock inc dword ptr [g_spy_cl_hits + 176]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_44_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100002ch
spy_cl_44_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 352]
spy_cl_44 ENDP

spy_cl_45 PROC
    lock inc dword ptr [g_spy_cl_hits + 180]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_45_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100002dh
spy_cl_45_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 360]
spy_cl_45 ENDP

spy_cl_46 PROC
    lock inc dword ptr [g_spy_cl_hits + 184]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_46_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100002eh
spy_cl_46_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 368]
spy_cl_46 ENDP

spy_cl_47 PROC
    lock inc dword ptr [g_spy_cl_hits + 188]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_47_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100002fh
spy_cl_47_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 376]
spy_cl_47 ENDP

spy_cl_48 PROC
    lock inc dword ptr [g_spy_cl_hits + 192]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_48_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000030h
spy_cl_48_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 384]
spy_cl_48 ENDP

spy_cl_49 PROC
    lock inc dword ptr [g_spy_cl_hits + 196]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_49_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000031h
spy_cl_49_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 392]
spy_cl_49 ENDP

spy_cl_50 PROC
    lock inc dword ptr [g_spy_cl_hits + 200]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_50_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000032h
spy_cl_50_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 400]
spy_cl_50 ENDP

spy_cl_51 PROC
    lock inc dword ptr [g_spy_cl_hits + 204]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_51_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000033h
spy_cl_51_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 408]
spy_cl_51 ENDP

spy_cl_52 PROC
    lock inc dword ptr [g_spy_cl_hits + 208]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_52_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000034h
spy_cl_52_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 416]
spy_cl_52 ENDP

spy_cl_53 PROC
    lock inc dword ptr [g_spy_cl_hits + 212]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_53_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000035h
spy_cl_53_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 424]
spy_cl_53 ENDP

spy_cl_54 PROC
    lock inc dword ptr [g_spy_cl_hits + 216]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_54_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000036h
spy_cl_54_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 432]
spy_cl_54 ENDP

spy_cl_55 PROC
    lock inc dword ptr [g_spy_cl_hits + 220]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_55_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000037h
spy_cl_55_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 440]
spy_cl_55 ENDP

spy_cl_56 PROC
    lock inc dword ptr [g_spy_cl_hits + 224]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_56_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000038h
spy_cl_56_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 448]
spy_cl_56 ENDP

spy_cl_57 PROC
    lock inc dword ptr [g_spy_cl_hits + 228]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_57_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000039h
spy_cl_57_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 456]
spy_cl_57 ENDP

spy_cl_58 PROC
    lock inc dword ptr [g_spy_cl_hits + 232]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_58_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100003ah
spy_cl_58_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 464]
spy_cl_58 ENDP

spy_cl_59 PROC
    lock inc dword ptr [g_spy_cl_hits + 236]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_59_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100003bh
spy_cl_59_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 472]
spy_cl_59 ENDP

spy_cl_60 PROC
    lock inc dword ptr [g_spy_cl_hits + 240]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_60_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100003ch
spy_cl_60_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 480]
spy_cl_60 ENDP

spy_cl_61 PROC
    lock inc dword ptr [g_spy_cl_hits + 244]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_61_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100003dh
spy_cl_61_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 488]
spy_cl_61 ENDP

spy_cl_62 PROC
    lock inc dword ptr [g_spy_cl_hits + 248]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_62_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100003eh
spy_cl_62_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 496]
spy_cl_62 ENDP

spy_cl_63 PROC
    lock inc dword ptr [g_spy_cl_hits + 252]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_63_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100003fh
spy_cl_63_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 504]
spy_cl_63 ENDP

spy_cl_64 PROC
    lock inc dword ptr [g_spy_cl_hits + 256]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_64_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000040h
spy_cl_64_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 512]
spy_cl_64 ENDP

spy_cl_65 PROC
    lock inc dword ptr [g_spy_cl_hits + 260]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_65_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000041h
spy_cl_65_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 520]
spy_cl_65 ENDP

spy_cl_66 PROC
    lock inc dword ptr [g_spy_cl_hits + 264]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_66_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000042h
spy_cl_66_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 528]
spy_cl_66 ENDP

spy_cl_67 PROC
    lock inc dword ptr [g_spy_cl_hits + 268]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_67_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000043h
spy_cl_67_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 536]
spy_cl_67 ENDP

spy_cl_68 PROC
    lock inc dword ptr [g_spy_cl_hits + 272]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_68_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000044h
spy_cl_68_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 544]
spy_cl_68 ENDP

spy_cl_69 PROC
    lock inc dword ptr [g_spy_cl_hits + 276]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_69_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000045h
spy_cl_69_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 552]
spy_cl_69 ENDP

spy_cl_70 PROC
    lock inc dword ptr [g_spy_cl_hits + 280]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_70_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000046h
spy_cl_70_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 560]
spy_cl_70 ENDP

spy_cl_71 PROC
    lock inc dword ptr [g_spy_cl_hits + 284]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_71_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000047h
spy_cl_71_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 568]
spy_cl_71 ENDP

spy_cl_72 PROC
    lock inc dword ptr [g_spy_cl_hits + 288]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_72_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000048h
spy_cl_72_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 576]
spy_cl_72 ENDP

spy_cl_73 PROC
    lock inc dword ptr [g_spy_cl_hits + 292]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_73_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 01000049h
spy_cl_73_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 584]
spy_cl_73 ENDP

spy_cl_74 PROC
    lock inc dword ptr [g_spy_cl_hits + 296]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_cl_74_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0100004ah
spy_cl_74_skip:
    jmp     qword ptr [g_spy_cl_snapshot + 592]
spy_cl_74 ENDP

spy_queue_0 PROC
    lock inc dword ptr [g_spy_queue_hits + 0]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_queue_0_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 02000000h
spy_queue_0_skip:
    jmp     qword ptr [g_spy_queue_snapshot + 0]
spy_queue_0 ENDP

spy_queue_1 PROC
    lock inc dword ptr [g_spy_queue_hits + 4]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_queue_1_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 02000001h
spy_queue_1_skip:
    jmp     qword ptr [g_spy_queue_snapshot + 8]
spy_queue_1 ENDP

spy_queue_2 PROC
    lock inc dword ptr [g_spy_queue_hits + 8]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_queue_2_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 02000002h
spy_queue_2_skip:
    jmp     qword ptr [g_spy_queue_snapshot + 16]
spy_queue_2 ENDP

spy_queue_3 PROC
    lock inc dword ptr [g_spy_queue_hits + 12]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_queue_3_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 02000003h
spy_queue_3_skip:
    jmp     qword ptr [g_spy_queue_snapshot + 24]
spy_queue_3 ENDP

spy_queue_4 PROC
    lock inc dword ptr [g_spy_queue_hits + 16]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_queue_4_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 02000004h
spy_queue_4_skip:
    jmp     qword ptr [g_spy_queue_snapshot + 32]
spy_queue_4 ENDP

spy_queue_5 PROC
    lock inc dword ptr [g_spy_queue_hits + 20]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_queue_5_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 02000005h
spy_queue_5_skip:
    jmp     qword ptr [g_spy_queue_snapshot + 40]
spy_queue_5 ENDP

spy_queue_6 PROC
    lock inc dword ptr [g_spy_queue_hits + 24]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_queue_6_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 02000006h
spy_queue_6_skip:
    jmp     qword ptr [g_spy_queue_snapshot + 48]
spy_queue_6 ENDP

spy_dxgi_0 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 0]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_0_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000000h
spy_dxgi_0_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 0]
spy_dxgi_0 ENDP

spy_dxgi_1 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 4]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_1_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000001h
spy_dxgi_1_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 8]
spy_dxgi_1 ENDP

spy_dxgi_2 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 8]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_2_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000002h
spy_dxgi_2_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 16]
spy_dxgi_2 ENDP

spy_dxgi_3 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 12]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_3_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000003h
spy_dxgi_3_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 24]
spy_dxgi_3 ENDP

spy_dxgi_4 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 16]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_4_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000004h
spy_dxgi_4_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 32]
spy_dxgi_4 ENDP

spy_dxgi_5 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 20]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_5_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000005h
spy_dxgi_5_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 40]
spy_dxgi_5 ENDP

spy_dxgi_6 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 24]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_6_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000006h
spy_dxgi_6_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 48]
spy_dxgi_6 ENDP

spy_dxgi_7 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 28]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_7_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000007h
spy_dxgi_7_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 56]
spy_dxgi_7 ENDP

spy_dxgi_8 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 32]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_8_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000008h
spy_dxgi_8_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 64]
spy_dxgi_8 ENDP

spy_dxgi_9 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 36]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_9_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000009h
spy_dxgi_9_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 72]
spy_dxgi_9 ENDP

spy_dxgi_10 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 40]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_10_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300000ah
spy_dxgi_10_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 80]
spy_dxgi_10 ENDP

spy_dxgi_11 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 44]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_11_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300000bh
spy_dxgi_11_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 88]
spy_dxgi_11 ENDP

spy_dxgi_12 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 48]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_12_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300000ch
spy_dxgi_12_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 96]
spy_dxgi_12 ENDP

spy_dxgi_13 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 52]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_13_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300000dh
spy_dxgi_13_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 104]
spy_dxgi_13 ENDP

spy_dxgi_14 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 56]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_14_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300000eh
spy_dxgi_14_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 112]
spy_dxgi_14 ENDP

spy_dxgi_15 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 60]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_15_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300000fh
spy_dxgi_15_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 120]
spy_dxgi_15 ENDP

spy_dxgi_16 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 64]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_16_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000010h
spy_dxgi_16_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 128]
spy_dxgi_16 ENDP

spy_dxgi_17 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 68]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_17_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000011h
spy_dxgi_17_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 136]
spy_dxgi_17 ENDP

spy_dxgi_18 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 72]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_18_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000012h
spy_dxgi_18_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 144]
spy_dxgi_18 ENDP

spy_dxgi_19 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 76]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_19_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000013h
spy_dxgi_19_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 152]
spy_dxgi_19 ENDP

spy_dxgi_20 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 80]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_20_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000014h
spy_dxgi_20_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 160]
spy_dxgi_20 ENDP

spy_dxgi_21 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 84]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_21_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000015h
spy_dxgi_21_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 168]
spy_dxgi_21 ENDP

spy_dxgi_22 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 88]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_22_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000016h
spy_dxgi_22_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 176]
spy_dxgi_22 ENDP

spy_dxgi_23 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 92]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_23_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000017h
spy_dxgi_23_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 184]
spy_dxgi_23 ENDP

spy_dxgi_24 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 96]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_24_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000018h
spy_dxgi_24_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 192]
spy_dxgi_24 ENDP

spy_dxgi_25 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 100]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_25_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 03000019h
spy_dxgi_25_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 200]
spy_dxgi_25 ENDP

spy_dxgi_26 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 104]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_26_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300001ah
spy_dxgi_26_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 208]
spy_dxgi_26 ENDP

spy_dxgi_27 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 108]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_27_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300001bh
spy_dxgi_27_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 216]
spy_dxgi_27 ENDP

spy_dxgi_28 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 112]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_28_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300001ch
spy_dxgi_28_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 224]
spy_dxgi_28 ENDP

spy_dxgi_29 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 116]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_29_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300001dh
spy_dxgi_29_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 232]
spy_dxgi_29 ENDP

spy_dxgi_30 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 120]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_30_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300001eh
spy_dxgi_30_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 240]
spy_dxgi_30 ENDP

spy_dxgi_31 PROC
    lock inc dword ptr [g_spy_dxgi_hits + 124]
    mov     r11d, 1
    lock xadd dword ptr [g_spy_trace_idx], r11d
    cmp     r11d, 00100000h
    jae     spy_dxgi_31_skip
    lea     r10, [g_spy_trace]
    mov     dword ptr [r10+r11*4], 0300001fh
spy_dxgi_31_skip:
    jmp     qword ptr [g_spy_dxgi_snapshot + 248]
spy_dxgi_31 ENDP

_TEXT ENDS

END
