// spy_workload.cpp — the four D12-G5 workloads that drive the WARP spy proxy.
//
//   device    DDI_REFERENCE.md §15.2 workload (a): D3D12CreateDevice and nothing else.
//             Settles #1 (which caps the runtime demands, in order), #5 and #6 (the
//             Interface/Version split and which token this Windows negotiates), #8
//             (whether pfnGetSupportedVersions is really a two-call query), #18.
//   queue     workload (b): + command queue, pool/recorder/list, Close. Settles #3 and #9.
//   window    workload (c): + swapchain, clear, present. Settles #2, #4, #7, #16. NO
//             SHADERS AT ALL, which is the point: it separates "the runtime always asks
//             for X" from "the app happened to need X".
//   triangle  workload (d): + a draw with TWO pipelines — one whose shaders are SM 5.1
//             DXBC compiled at runtime by D3DCompile, one whose shaders are SM 6.0 DXIL
//             compiled at build time by dxc. Settles #14 / Q1 for both encodings in one
//             process, which a single-shader-model run cannot do.
//
// ⚠ Why these and not `dx-samples-research-only/.../D3D12HelloWorld`, which GATES.md §4.6
// names: that sample carries the Agility SDK exports
// (`D3D12HelloWindow.cpp:15-16`: `D3D12SDKVersion = 618`, `D3D12SDKPath = ".\\D3D12\\"`),
// so whether the experiment runs against THIS Windows build's D3D12Core.dll or against a
// NuGet one depends on whether a `D3D12\` directory happens to sit beside the exe. This
// gate is a measurement OF the shipping runtime; a silent runtime substitution would
// invalidate every line of the log. These probes carry no such export and need no NuGet
// package (the samples need `include/d3dx12/d3dx12.h` from Microsoft.Direct3D.D3D12
// 1.618.3, which is not vendored in this tree).
//
// ⛔ `window` and `triangle` create a window, so they must run in SESSION 1 via a cloned
// scheduled task — a windowed run launched from win_exec lands in session 0, which has no
// desktop, and fakes a driver regression (memory lease-gate-falsified-60th).
//
// build: build.ps1

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <dxgidebug.h>
#include <d3dcompiler.h>
#include <stdio.h>
#include <string.h>

#include "spy_workload_vs.h"  // g_vs_main — DXIL SM 6.0, generated by dxc -Fh
#include "spy_workload_ps.h"  // g_ps_main

#define FRAME_COUNT 2

static int g_fail;
static void check(HRESULT hr, const char* what) {
    printf("%-46s 0x%08lx %s\n", what, (unsigned long)hr, SUCCEEDED(hr) ? "OK" : "FAIL");
    fflush(stdout);
    if (FAILED(hr)) ++g_fail;
}
#define CHECK(expr) check((expr), #expr)
#define MUST(expr)                    \
    do {                              \
        HRESULT _hr = (expr);         \
        check(_hr, #expr);            \
        if (FAILED(_hr)) return _hr;  \
    } while (0)

struct Args {
    const char* mode = "device";
    bool warp = false;
    int adapter = -1;
    int frames = 5;
    bool debug = false;  // enable the D3D12 debug layer -- the retail runtime and the
                         // debug layer enforce DIFFERENT caps rules, and telling them
                         // apart is the whole point of the `range` arm.
    int hold = 0;  // seconds to stay alive after setup, so the caller can read the
                   // process's loaded-module list. "Which d3d10warp.dll is mapped" is the
                   // check DDI_REFERENCE.md §15.2 demands before trusting a null result.
};

static IDXGIFactory4* g_factory;
static IDXGIAdapter1* g_adapter;
static ID3D12Device* g_device;
static ID3D12CommandQueue* g_queue;
static ID3D12CommandAllocator* g_alloc;
static ID3D12GraphicsCommandList* g_list;
static IDXGISwapChain3* g_swap;
static ID3D12DescriptorHeap* g_rtvHeap;
static ID3D12Resource* g_rt[FRAME_COUNT];
static UINT g_rtvStride;
static ID3D12Fence* g_fence;
static UINT64 g_fenceValue;
static HANDLE g_fenceEvent;
static HWND g_hwnd;
static ID3D12RootSignature* g_rootSig;
static ID3D12PipelineState* g_psoDxil;
static ID3D12PipelineState* g_psoDxbc;
static ID3D12Resource* g_vb;
static D3D12_VERTEX_BUFFER_VIEW g_vbv;

static const UINT kWidth = 640, kHeight = 480;

// ⭐ Why this exists: a bare HRESULT from CreateSwapChainForHwnd is not a diagnosis.
// 2026-08-07's first Helios D3D12 run returned E_INVALIDARG from a descriptor that the
// SAME binary presents 20 frames from on WARP (run-C.txt), so the parameters are legal
// and the rejection is adapter-specific -- but the driver's own refusal counters all read
// zero, i.e. DXGI refused BEFORE reaching pfnPresent and nothing in this driver saw the
// reason. The DXGI info queue is the only place that reason is written down.
//
// ⚠ DXGIGetDebugInterface1 is resolved by name rather than linked: it lives in dxgi.dll
// but only answers when the Graphics Tools optional feature is present, and a probe that
// fails to START because a diagnostic export is missing has destroyed the measurement it
// was added to take.
static void dump_dxgi_messages(const char* when) {
    HMODULE dxgi = GetModuleHandleW(L"dxgi.dll");
    if (!dxgi) return;
    typedef HRESULT(WINAPI * PFN_GET)(UINT, REFIID, void**);
    PFN_GET get = (PFN_GET)GetProcAddress(dxgi, "DXGIGetDebugInterface1");
    if (!get) {
        printf("[dxgi-info] DXGIGetDebugInterface1 absent -- no Graphics Tools?\n");
        return;
    }
    IDXGIInfoQueue* q = nullptr;
    if (FAILED(get(0, IID_PPV_ARGS(&q))) || !q) {
        printf("[dxgi-info] no IDXGIInfoQueue (factory not created with "
               "DXGI_CREATE_FACTORY_DEBUG?)\n");
        return;
    }
    const UINT64 n = q->GetNumStoredMessages(DXGI_DEBUG_ALL);
    printf("[dxgi-info] %s: %llu stored message(s)\n", when, (unsigned long long)n);
    for (UINT64 i = 0; i < n; ++i) {
        SIZE_T len = 0;
        if (FAILED(q->GetMessage(DXGI_DEBUG_ALL, i, nullptr, &len)) || len == 0) continue;
        DXGI_INFO_QUEUE_MESSAGE* m = (DXGI_INFO_QUEUE_MESSAGE*)malloc(len);
        if (!m) continue;
        if (SUCCEEDED(q->GetMessage(DXGI_DEBUG_ALL, i, m, &len))) {
            printf("[dxgi-info] sev=%d cat=%d id=%d: %.*s\n", (int)m->Severity,
                   (int)m->Category, (int)m->ID, (int)m->DescriptionByteLength,
                   m->pDescription);
        }
        free(m);
    }
    fflush(stdout);
    q->Release();
}

static HRESULT pick_adapter(const Args& a) {
    // The info queue only records anything when the FACTORY carries the debug flag, so
    // --debug has to change how the factory is made, not just call EnableDebugLayer.
    if (a.debug) {
        MUST(CreateDXGIFactory2(DXGI_CREATE_FACTORY_DEBUG, IID_PPV_ARGS(&g_factory)));
    } else {
        MUST(CreateDXGIFactory1(IID_PPV_ARGS(&g_factory)));
    }
    if (a.warp) {
        IDXGIAdapter* warp = nullptr;
        MUST(g_factory->EnumWarpAdapter(IID_PPV_ARGS(&warp)));
        MUST(warp->QueryInterface(IID_PPV_ARGS(&g_adapter)));
        warp->Release();
    } else {
        UINT i = (a.adapter < 0) ? 0 : (UINT)a.adapter;
        MUST(g_factory->EnumAdapters1(i, &g_adapter));
    }
    DXGI_ADAPTER_DESC1 d = {};
    g_adapter->GetDesc1(&d);
    printf("adapter: %ls  vid=0x%04x did=0x%04x luid=%08lx:%08lx flags=0x%x\n",
           d.Description, d.VendorId, d.DeviceId, (unsigned long)d.AdapterLuid.HighPart,
           (unsigned long)d.AdapterLuid.LowPart, d.Flags);
    return S_OK;
}

static HRESULT make_device() {
    MUST(D3D12CreateDevice(g_adapter, D3D_FEATURE_LEVEL_11_0, IID_PPV_ARGS(&g_device)));
    D3D12_FEATURE_DATA_SHADER_MODEL sm = {D3D_SHADER_MODEL_6_8};
    while (sm.HighestShaderModel > D3D_SHADER_MODEL_5_1
           && FAILED(g_device->CheckFeatureSupport(D3D12_FEATURE_SHADER_MODEL, &sm,
                                                   sizeof(sm))))
        sm.HighestShaderModel = (D3D_SHADER_MODEL)(sm.HighestShaderModel - 1);
    D3D12_FEATURE_DATA_FEATURE_LEVELS fl = {};
    D3D_FEATURE_LEVEL levels[] = {D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_11_1,
                                  D3D_FEATURE_LEVEL_12_0, D3D_FEATURE_LEVEL_12_1,
                                  D3D_FEATURE_LEVEL_12_2};
    fl.NumFeatureLevels = 5;
    fl.pFeatureLevelsRequested = levels;
    g_device->CheckFeatureSupport(D3D12_FEATURE_FEATURE_LEVELS, &fl, sizeof(fl));
    printf("device: HighestShaderModel=0x%x MaxSupportedFeatureLevel=0x%x\n",
           (unsigned)sm.HighestShaderModel, (unsigned)fl.MaxSupportedFeatureLevel);
    // Read the tiers back at the API. If the spy's `range` mutation reaches this print,
    // the runtime passed an out-of-range tier straight through to the application -- which
    // is the "advertising a capability that is not backed" rule one layer up.
    D3D12_FEATURE_DATA_D3D12_OPTIONS o = {};
    if (SUCCEEDED(g_device->CheckFeatureSupport(D3D12_FEATURE_D3D12_OPTIONS, &o, sizeof(o))))
        printf("device: API ResourceBindingTier=%u TiledResourcesTier=%u "
               "ResourceHeapTier=%u ConservativeRasterizationTier=%u\n",
               (unsigned)o.ResourceBindingTier, (unsigned)o.TiledResourcesTier,
               (unsigned)o.ResourceHeapTier, (unsigned)o.ConservativeRasterizationTier);
    return S_OK;
}

static HRESULT make_queue() {
    D3D12_COMMAND_QUEUE_DESC qd = {};
    qd.Type = D3D12_COMMAND_LIST_TYPE_DIRECT;
    MUST(g_device->CreateCommandQueue(&qd, IID_PPV_ARGS(&g_queue)));
    MUST(g_device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,
                                          IID_PPV_ARGS(&g_alloc)));
    MUST(g_device->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT, g_alloc, nullptr,
                                     IID_PPV_ARGS(&g_list)));
    MUST(g_list->Close());
    return S_OK;
}

static LRESULT CALLBACK wndproc(HWND h, UINT m, WPARAM w, LPARAM l) {
    if (m == WM_DESTROY) {
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProc(h, m, w, l);
}

static HRESULT make_window_and_swapchain() {
    WNDCLASSEXW wc = {};
    wc.cbSize = sizeof(wc);
    wc.lpfnWndProc = wndproc;
    wc.hInstance = GetModuleHandleW(nullptr);
    wc.hCursor = LoadCursorW(nullptr, MAKEINTRESOURCEW(32512));  // IDC_ARROW, W form
    wc.lpszClassName = L"HeliosD12SpyWorkload";
    RegisterClassExW(&wc);
    RECT r = {0, 0, (LONG)kWidth, (LONG)kHeight};
    AdjustWindowRect(&r, WS_OVERLAPPEDWINDOW, FALSE);
    g_hwnd = CreateWindowW(wc.lpszClassName, L"Helios D12-G5 spy workload",
                           WS_OVERLAPPEDWINDOW, CW_USEDEFAULT, CW_USEDEFAULT,
                           r.right - r.left, r.bottom - r.top, nullptr, nullptr,
                           wc.hInstance, nullptr);
    if (!g_hwnd) {
        printf("CreateWindow failed, gle=%lu\n", GetLastError());
        return E_FAIL;
    }
    ShowWindow(g_hwnd, SW_SHOW);

    DXGI_SWAP_CHAIN_DESC1 sd = {};
    sd.BufferCount = FRAME_COUNT;
    sd.Width = kWidth;
    sd.Height = kHeight;
    sd.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    sd.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
    sd.SwapEffect = DXGI_SWAP_EFFECT_FLIP_DISCARD;
    sd.SampleDesc.Count = 1;
    IDXGISwapChain1* sc1 = nullptr;
    MUST(g_factory->CreateSwapChainForHwnd(g_queue, g_hwnd, &sd, nullptr, nullptr, &sc1));
    MUST(sc1->QueryInterface(IID_PPV_ARGS(&g_swap)));
    sc1->Release();
    g_factory->MakeWindowAssociation(g_hwnd, DXGI_MWA_NO_ALT_ENTER);

    D3D12_DESCRIPTOR_HEAP_DESC hd = {};
    hd.NumDescriptors = FRAME_COUNT;
    hd.Type = D3D12_DESCRIPTOR_HEAP_TYPE_RTV;
    MUST(g_device->CreateDescriptorHeap(&hd, IID_PPV_ARGS(&g_rtvHeap)));
    g_rtvStride = g_device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_RTV);
    printf("RTV descriptor increment = %u\n", g_rtvStride);
    D3D12_CPU_DESCRIPTOR_HANDLE h = g_rtvHeap->GetCPUDescriptorHandleForHeapStart();
    printf("RTV heap start CPU handle = 0x%zx\n", (size_t)h.ptr);
    for (UINT i = 0; i < FRAME_COUNT; ++i) {
        MUST(g_swap->GetBuffer(i, IID_PPV_ARGS(&g_rt[i])));
        g_device->CreateRenderTargetView(g_rt[i], nullptr, h);
        h.ptr += g_rtvStride;
    }
    MUST(g_device->CreateFence(0, D3D12_FENCE_FLAG_NONE, IID_PPV_ARGS(&g_fence)));
    g_fenceValue = 1;
    g_fenceEvent = CreateEventW(nullptr, FALSE, FALSE, nullptr);
    return S_OK;
}

static void wait_gpu() {
    const UINT64 v = g_fenceValue++;
    g_queue->Signal(g_fence, v);
    if (g_fence->GetCompletedValue() < v) {
        g_fence->SetEventOnCompletion(v, g_fenceEvent);
        WaitForSingleObject(g_fenceEvent, 5000);
    }
}

static void default_blend(D3D12_BLEND_DESC* b) {
    memset(b, 0, sizeof(*b));
    for (int i = 0; i < 8; ++i) {
        b->RenderTarget[i].SrcBlend = D3D12_BLEND_ONE;
        b->RenderTarget[i].DestBlend = D3D12_BLEND_ZERO;
        b->RenderTarget[i].BlendOp = D3D12_BLEND_OP_ADD;
        b->RenderTarget[i].SrcBlendAlpha = D3D12_BLEND_ONE;
        b->RenderTarget[i].DestBlendAlpha = D3D12_BLEND_ZERO;
        b->RenderTarget[i].BlendOpAlpha = D3D12_BLEND_OP_ADD;
        b->RenderTarget[i].LogicOp = D3D12_LOGIC_OP_NOOP;
        b->RenderTarget[i].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;
    }
}

static HRESULT make_pipelines() {
    D3D12_ROOT_SIGNATURE_DESC rs = {};
    rs.Flags = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;
    ID3DBlob* sig = nullptr;
    ID3DBlob* err = nullptr;
    MUST(D3D12SerializeRootSignature(&rs, D3D_ROOT_SIGNATURE_VERSION_1, &sig, &err));
    MUST(g_device->CreateRootSignature(0, sig->GetBufferPointer(), sig->GetBufferSize(),
                                       IID_PPV_ARGS(&g_rootSig)));
    sig->Release();

    D3D12_INPUT_ELEMENT_DESC il[] = {
        {"POSITION", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 0,
         D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
        {"COLOR", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 16,
         D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
    };
    D3D12_GRAPHICS_PIPELINE_STATE_DESC p = {};
    p.pRootSignature = g_rootSig;
    default_blend(&p.BlendState);
    p.SampleMask = UINT_MAX;
    p.RasterizerState.FillMode = D3D12_FILL_MODE_SOLID;
    p.RasterizerState.CullMode = D3D12_CULL_MODE_NONE;
    p.RasterizerState.DepthClipEnable = TRUE;
    p.DepthStencilState.DepthEnable = FALSE;
    p.DepthStencilState.StencilEnable = FALSE;
    p.InputLayout.pInputElementDescs = il;
    p.InputLayout.NumElements = 2;
    p.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
    p.NumRenderTargets = 1;
    p.RTVFormats[0] = DXGI_FORMAT_R8G8B8A8_UNORM;
    p.SampleDesc.Count = 1;

    // Arm 1: DXIL, shader model 6.0, compiled at BUILD time by dxc.
    p.VS.pShaderBytecode = g_vs_main;
    p.VS.BytecodeLength = sizeof(g_vs_main);
    p.PS.pShaderBytecode = g_ps_main;
    p.PS.BytecodeLength = sizeof(g_ps_main);
    printf("SM 6.0 DXIL blob: vs dword[0]=0x%08x (%s) size=%zu\n", *(const UINT*)g_vs_main,
           (*(const UINT*)g_vs_main == 0x43425844u) ? "DXBC container" : "raw",
           sizeof(g_vs_main));
    MUST(g_device->CreateGraphicsPipelineState(&p, IID_PPV_ARGS(&g_psoDxil)));

    // Arm 2: DXBC, shader model 5.1, compiled at RUN time by D3DCompile. If the runtime
    // hands the driver a different encoding for the two, the spy log shows it.
    static const char kHlsl[] =
        "struct ps_in { float4 position : SV_POSITION; float4 colour : COLOR; };\n"
        "struct ps_in vs_main(float4 position : POSITION, float4 colour : COLOR) {\n"
        "  struct ps_in o; o.position = position; o.colour = colour; return o; }\n"
        "float4 ps_main(struct ps_in i) : SV_TARGET { return i.colour; }\n";
    ID3DBlob* vs51 = nullptr;
    ID3DBlob* ps51 = nullptr;
    HRESULT hv = D3DCompile(kHlsl, sizeof(kHlsl) - 1, "spy51", nullptr, nullptr, "vs_main",
                            "vs_5_1", 0, 0, &vs51, &err);
    HRESULT hp = D3DCompile(kHlsl, sizeof(kHlsl) - 1, "spy51", nullptr, nullptr, "ps_main",
                            "ps_5_1", 0, 0, &ps51, &err);
    check(hv, "D3DCompile vs_5_1");
    check(hp, "D3DCompile ps_5_1");
    if (SUCCEEDED(hv) && SUCCEEDED(hp)) {
        printf("SM 5.1 DXBC blob: vs dword[0]=0x%08x (%s) size=%zu\n",
               *(const UINT*)vs51->GetBufferPointer(),
               (*(const UINT*)vs51->GetBufferPointer() == 0x43425844u) ? "DXBC container"
                                                                      : "raw",
               vs51->GetBufferSize());
        p.VS.pShaderBytecode = vs51->GetBufferPointer();
        p.VS.BytecodeLength = vs51->GetBufferSize();
        p.PS.pShaderBytecode = ps51->GetBufferPointer();
        p.PS.BytecodeLength = ps51->GetBufferSize();
        CHECK(g_device->CreateGraphicsPipelineState(&p, IID_PPV_ARGS(&g_psoDxbc)));
        vs51->Release();
        ps51->Release();
    }

    struct V {
        float pos[4], col[4];
    };
    static const V verts[3] = {
        {{0.0f, 0.55f, 0.0f, 1.0f}, {1.0f, 0.0f, 0.0f, 1.0f}},
        {{0.55f, -0.55f, 0.0f, 1.0f}, {0.0f, 1.0f, 0.0f, 1.0f}},
        {{-0.55f, -0.55f, 0.0f, 1.0f}, {0.0f, 0.0f, 1.0f, 1.0f}},
    };
    D3D12_HEAP_PROPERTIES hp2 = {};
    hp2.Type = D3D12_HEAP_TYPE_UPLOAD;
    D3D12_RESOURCE_DESC rd = {};
    rd.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
    rd.Width = sizeof(verts);
    rd.Height = 1;
    rd.DepthOrArraySize = 1;
    rd.MipLevels = 1;
    rd.Format = DXGI_FORMAT_UNKNOWN;
    rd.SampleDesc.Count = 1;
    rd.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
    MUST(g_device->CreateCommittedResource(&hp2, D3D12_HEAP_FLAG_NONE, &rd,
                                           D3D12_RESOURCE_STATE_GENERIC_READ, nullptr,
                                           IID_PPV_ARGS(&g_vb)));
    void* mapped = nullptr;
    D3D12_RANGE none = {0, 0};
    MUST(g_vb->Map(0, &none, &mapped));
    memcpy(mapped, verts, sizeof(verts));
    g_vb->Unmap(0, nullptr);
    g_vbv.BufferLocation = g_vb->GetGPUVirtualAddress();
    g_vbv.StrideInBytes = sizeof(V);
    g_vbv.SizeInBytes = sizeof(verts);
    return S_OK;
}

// ⭐ `share` — which kernel object does the flip-model swapchain have no handle for?
//
// 2026-08-07: CreateSwapChainForHwnd on Helios failed E_INVALIDARG, and the ONLY reason
// written down anywhere was in ETW, not in any HRESULT: dxgkrnl AzureTriage
// "Input object handle is NULL. Returning 0xC000000D" immediately followed by the
// Microsoft-Windows-Direct3D12 journal entry Message="ShareObjects" Code=0xC000000D.
// So the runtime called D3DKMTShareObjects on a swapchain object that has NO kernel
// handle. A flip-model swapchain shares TWO kinds of object — the back buffers and the
// present fence — and the aggregate failure cannot say which.
//
// ⛔ This arm exists because attributing it by reading the driver is exactly the
// premise-sharing trap the 85th session recorded: `fence.rs`'s module doc already
// ASSERTS that "sharing a fence is D3DKMTShareObjects on the runtime's own kernel
// handle — the one the driver never sees", which if believed would attribute this to
// the resource without measuring. Each object is shared here on its own, so the two
// HRESULTs are independent readings.
static void probe_sharing() {
    D3D12_HEAP_PROPERTIES hp = {};
    hp.Type = D3D12_HEAP_TYPE_DEFAULT;
    D3D12_RESOURCE_DESC rd = {};
    rd.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
    rd.Width = kWidth;
    rd.Height = kHeight;
    rd.DepthOrArraySize = 1;
    rd.MipLevels = 1;
    rd.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    rd.SampleDesc.Count = 1;
    rd.Layout = D3D12_TEXTURE_LAYOUT_UNKNOWN;
    rd.Flags = D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET;

    // (a) the back-buffer shape: a SHARED committed render target, then its NT handle.
    ID3D12Resource* res = nullptr;
    HRESULT hr = g_device->CreateCommittedResource(
        &hp, D3D12_HEAP_FLAG_SHARED, &rd, D3D12_RESOURCE_STATE_COMMON, nullptr,
        IID_PPV_ARGS(&res));
    check(hr, "share: CreateCommittedResource(HEAP_FLAG_SHARED, RT 640x480 RGBA8)");
    if (SUCCEEDED(hr)) {
        HANDLE h = nullptr;
        check(g_device->CreateSharedHandle(res, nullptr, GENERIC_ALL, nullptr, &h),
              "share: CreateSharedHandle(resource)");
        if (h) CloseHandle(h);
        res->Release();
    }

    // (b) the present-fence shape.
    ID3D12Fence* f = nullptr;
    hr = g_device->CreateFence(0, D3D12_FENCE_FLAG_SHARED, IID_PPV_ARGS(&f));
    check(hr, "share: CreateFence(FENCE_FLAG_SHARED)");
    if (SUCCEEDED(hr)) {
        HANDLE h = nullptr;
        check(g_device->CreateSharedHandle(f, nullptr, GENERIC_ALL, nullptr, &h),
              "share: CreateSharedHandle(fence)");
        if (h) CloseHandle(h);
        f->Release();
    }

    // (c) the control: a NON-shared committed resource of the same shape, so a failure
    //     in (a) can be attributed to the SHARED flag rather than to the descriptor.
    ID3D12Resource* plain = nullptr;
    check(g_device->CreateCommittedResource(&hp, D3D12_HEAP_FLAG_NONE, &rd,
                                            D3D12_RESOURCE_STATE_COMMON, nullptr,
                                            IID_PPV_ARGS(&plain)),
          "share: CreateCommittedResource(HEAP_FLAG_NONE, same desc) [control]");
    if (plain) plain->Release();
}

static void render_frame(int frame, bool draw) {
    UINT idx = g_swap->GetCurrentBackBufferIndex();
    g_alloc->Reset();
    g_list->Reset(g_alloc, draw ? g_psoDxil : nullptr);

    D3D12_RESOURCE_BARRIER b = {};
    b.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
    b.Transition.pResource = g_rt[idx];
    b.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
    b.Transition.StateBefore = D3D12_RESOURCE_STATE_PRESENT;
    b.Transition.StateAfter = D3D12_RESOURCE_STATE_RENDER_TARGET;
    g_list->ResourceBarrier(1, &b);

    D3D12_CPU_DESCRIPTOR_HANDLE rtv = g_rtvHeap->GetCPUDescriptorHandleForHeapStart();
    rtv.ptr += (SIZE_T)idx * g_rtvStride;
    const float clear[4] = {0.125f, 0.375f, 0.75f, 1.0f};
    g_list->OMSetRenderTargets(1, &rtv, FALSE, nullptr);
    g_list->ClearRenderTargetView(rtv, clear, 0, nullptr);

    if (draw) {
        D3D12_VIEWPORT vp = {0.0f, 0.0f, (float)kWidth, (float)kHeight, 0.0f, 1.0f};
        D3D12_RECT sc = {0, 0, (LONG)kWidth, (LONG)kHeight};
        g_list->RSSetViewports(1, &vp);
        g_list->RSSetScissorRects(1, &sc);
        g_list->SetGraphicsRootSignature(g_rootSig);
        g_list->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        g_list->IASetVertexBuffers(0, 1, &g_vbv);
        g_list->DrawInstanced(3, 1, 0, 0);
        if (g_psoDxbc) {  // second draw, SM 5.1 DXBC pipeline
            g_list->SetPipelineState(g_psoDxbc);
            g_list->DrawInstanced(3, 1, 0, 0);
        }
    }

    b.Transition.StateBefore = D3D12_RESOURCE_STATE_RENDER_TARGET;
    b.Transition.StateAfter = D3D12_RESOURCE_STATE_PRESENT;
    g_list->ResourceBarrier(1, &b);
    g_list->Close();
    ID3D12CommandList* lists[] = {g_list};
    g_queue->ExecuteCommandLists(1, lists);
    HRESULT hr = g_swap->Present(1, 0);
    if (FAILED(hr)) {
        printf("Present(frame %d) -> 0x%08lx\n", frame, (unsigned long)hr);
        ++g_fail;
    }
    wait_gpu();
}

static void release_all() {
    if (g_vb) g_vb->Release();
    if (g_psoDxbc) g_psoDxbc->Release();
    if (g_psoDxil) g_psoDxil->Release();
    if (g_rootSig) g_rootSig->Release();
    for (int i = 0; i < FRAME_COUNT; ++i)
        if (g_rt[i]) g_rt[i]->Release();
    if (g_rtvHeap) g_rtvHeap->Release();
    if (g_swap) g_swap->Release();
    if (g_fence) g_fence->Release();
    if (g_fenceEvent) CloseHandle(g_fenceEvent);
    if (g_list) g_list->Release();
    if (g_alloc) g_alloc->Release();
    if (g_queue) g_queue->Release();
    if (g_device) g_device->Release();
    if (g_adapter) g_adapter->Release();
    if (g_factory) g_factory->Release();
    if (g_hwnd) DestroyWindow(g_hwnd);
}

int main(int argc, char** argv) {
    Args a;
    for (int i = 1; i < argc; ++i) {
        if (!_stricmp(argv[i], "--warp") || !_stricmp(argv[i], "/warp")) a.warp = true;
        else if (!_stricmp(argv[i], "--adapter") && i + 1 < argc) a.adapter = atoi(argv[++i]);
        else if (!_stricmp(argv[i], "--frames") && i + 1 < argc) a.frames = atoi(argv[++i]);
        else if (!_stricmp(argv[i], "--hold") && i + 1 < argc) a.hold = atoi(argv[++i]);
        else if (!_stricmp(argv[i], "--debug")) a.debug = true;
        else a.mode = argv[i];
    }
    printf("== spy_workload mode=%s warp=%d adapter=%d frames=%d pid=%lu\n", a.mode, a.warp,
           a.adapter, a.frames, GetCurrentProcessId());

    if (a.debug) {
        ID3D12Debug* dbg = nullptr;
        HRESULT hr = D3D12GetDebugInterface(IID_PPV_ARGS(&dbg));
        check(hr, "D3D12GetDebugInterface");
        if (SUCCEEDED(hr)) { dbg->EnableDebugLayer(); dbg->Release(); }
    }

    bool wantQueue = _stricmp(a.mode, "device") != 0;
    bool wantWindow = !_stricmp(a.mode, "window") || !_stricmp(a.mode, "triangle");
    bool wantDraw = !_stricmp(a.mode, "triangle");

    if (FAILED(pick_adapter(a))) { release_all(); return 2; }
    if (FAILED(make_device())) { release_all(); return 3; }
    if (wantQueue && FAILED(make_queue())) { release_all(); return 4; }
    if (wantWindow && FAILED(make_window_and_swapchain())) {
        dump_dxgi_messages("after make_window_and_swapchain failed");
        release_all();
        return 5;
    }
    if (wantDraw && FAILED(make_pipelines())) { release_all(); return 6; }
    if (!_stricmp(a.mode, "share")) probe_sharing();
    if (a.debug) dump_dxgi_messages("after setup");

    if (wantWindow) {
        for (int f = 0; f < a.frames; ++f) {
            MSG m;
            while (PeekMessageW(&m, nullptr, 0, 0, PM_REMOVE)) {
                TranslateMessage(&m);
                DispatchMessageW(&m);
            }
            render_frame(f, wantDraw);
            printf("frame %d presented\n", f);
            fflush(stdout);
        }
        wait_gpu();
    }

    if (a.hold > 0) {
        printf("holding %d s for module inspection (pid %lu)\n", a.hold,
               GetCurrentProcessId());
        fflush(stdout);
        Sleep((DWORD)a.hold * 1000);
    }

    release_all();
    printf("== spy_workload done, failures=%d\n", g_fail);
    return g_fail ? 1 : 0;
}
