// tools/d3d12_bridge_probe.cpp — gate D12-G1, the engine gate.
//
// Proves the engine path `umd12` will actually use, one layer BELOW the DDI:
//
//     LoadLibrary("helios_vkd3d.dll")
//       -> helios_vkd3d_create_device(luid, IID_ID3D12Device, &device)
//       -> clear + draw into an offscreen ID3D12Resource
//       -> copy to a READBACK heap, Map, and compare the pixels
//
// There is no d3d12.dll, no D3D12 runtime, no DXGI swapchain and nothing on
// screen. Under DECISIONS.md D2 this and D12-G2 are the only early truth about
// whether vkd3d runs on venus, so every step logs its own line: a failure must be
// attributable to one step, not to "the probe".
//
// ⛔ Deliberately does NOT link d3d12.lib — the whole point is that the device
// comes from helios_vkd3d.dll, not from the OS runtime. IIDs come from
// __uuidof(), so dxguid.lib is not needed either. dxgi.lib is linked for ONE
// purpose: reading the Helios adapter's LUID, which the runtime will hand
// umd12 for free. That is a probe convenience, not part of the path under test.
//
// Build: tmp/dx12/build-g1-probe.ps1 (dxc -T {vs,ps}_6_0 -Fh, then cl).
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <stdio.h>
#include <stdint.h>

#include "d3d12_bridge_probe_vs.h"   // g_vs_main — generated by dxc -Fh
#include "d3d12_bridge_probe_ps.h"   // g_ps_main — generated by dxc -Fh

#pragma comment(lib, "dxgi.lib")

// ---- the two Helios exports (DECISIONS.md D4) -------------------------------
typedef HRESULT(*PFN_HELIOS_VKD3D_CREATE_DEVICE)(LUID adapter_luid, REFIID iid, void **device);
typedef HRESULT(*PFN_HELIOS_VKD3D_SERIALIZE_ROOT_SIGNATURE)(
        const D3D12_ROOT_SIGNATURE_DESC *desc, D3D_ROOT_SIGNATURE_VERSION version,
        ID3DBlob **blob, ID3DBlob **error_blob);

static const wchar_t *DEFAULT_DLL = L"Z:\\tmp\\dx12\\build\\vkd3d-win64\\libs\\d3d12core\\helios_vkd3d.dll";

// The render target, and the two colours the readback must find.
static const UINT   RT_W = 256, RT_H = 256;
// Chosen so every channel is exact in 8-bit UNORM: no rounding tolerance is
// being spent to hide a real colour-space bug.
static const float  CLEAR_RGBA[4] = { 32.0f / 255.0f, 96.0f / 255.0f, 192.0f / 255.0f, 1.0f };
static const BYTE   EXPECT_CLEAR[4] = { 32, 96, 192, 255 };
static const BYTE   EXPECT_TRI[4]   = { 255, 128, 64, 255 };

struct Vertex { float pos[4]; float col[4]; };

static int g_step = 0;
static int g_failures = 0;

#define STEP(fmt, ...)  printf("[%02d] " fmt "\n", ++g_step, __VA_ARGS__)
#define FAILSTEP(fmt, ...)  do { printf("[%02d] FAIL: " fmt "\n", ++g_step, __VA_ARGS__); g_failures++; } while (0)

static bool check(HRESULT hr, const char *what)
{
    if (SUCCEEDED(hr)) { printf("[%02d] ok    %s\n", ++g_step, what); return true; }
    printf("[%02d] FAIL  %s -> hr=0x%08lx\n", ++g_step, what, (unsigned long)hr);
    g_failures++;
    return false;
}

static const char *sm_name(D3D_SHADER_MODEL sm)
{
    switch ((int)sm) {
    case 0x60: return "6.0"; case 0x61: return "6.1"; case 0x62: return "6.2";
    case 0x63: return "6.3"; case 0x64: return "6.4"; case 0x65: return "6.5";
    case 0x66: return "6.6"; case 0x67: return "6.7"; case 0x68: return "6.8";
    case 0x51: return "5.1"; default: return "?";
    }
}

static const char *fl_name(D3D_FEATURE_LEVEL fl)
{
    switch ((int)fl) {
    case 0xb000: return "11_0"; case 0xb100: return "11_1";
    case 0xc000: return "12_0"; case 0xc100: return "12_1"; case 0xc200: return "12_2";
    default: return "?";
    }
}

// Report what the engine believes it can do. These are exactly the caps the DDI
// arm must answer at P3/G7 (H4), so recording them here gives that work a
// zero-point — and the SHADER_MODEL line is the end-to-end confirmation of H5
// that the Vulkan-level driverID probe could only predict.
static void dump_caps(ID3D12Device *dev)
{
    D3D_FEATURE_LEVEL levels[] = { D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_11_1,
                                   D3D_FEATURE_LEVEL_12_0, D3D_FEATURE_LEVEL_12_1,
                                   D3D_FEATURE_LEVEL_12_2 };
    D3D12_FEATURE_DATA_FEATURE_LEVELS fls = {};
    fls.NumFeatureLevels = ARRAYSIZE(levels);
    fls.pFeatureLevelsRequested = levels;
    if (SUCCEEDED(dev->CheckFeatureSupport(D3D12_FEATURE_FEATURE_LEVELS, &fls, sizeof(fls))))
        printf("       caps: MaxSupportedFeatureLevel = %s\n", fl_name(fls.MaxSupportedFeatureLevel));
    else
        printf("       caps: FEATURE_LEVELS query FAILED\n");

    // The runtime clamps downward from whatever is asked for, so walk down until
    // one succeeds; an SDK that knows a newer model than the driver returns
    // E_INVALIDARG rather than clamping.
    const D3D_SHADER_MODEL ask[] = { (D3D_SHADER_MODEL)0x68, (D3D_SHADER_MODEL)0x67,
                                     (D3D_SHADER_MODEL)0x66, (D3D_SHADER_MODEL)0x60 };
    for (int i = 0; i < ARRAYSIZE(ask); i++) {
        D3D12_FEATURE_DATA_SHADER_MODEL sm = {};
        sm.HighestShaderModel = ask[i];
        if (SUCCEEDED(dev->CheckFeatureSupport(D3D12_FEATURE_SHADER_MODEL, &sm, sizeof(sm)))) {
            printf("       caps: HighestShaderModel = %s (asked %s)\n",
                   sm_name(sm.HighestShaderModel), sm_name(ask[i]));
            break;
        }
    }

    D3D12_FEATURE_DATA_D3D12_OPTIONS o = {};
    if (SUCCEEDED(dev->CheckFeatureSupport(D3D12_FEATURE_D3D12_OPTIONS, &o, sizeof(o))))
        printf("       caps: ResourceBindingTier=%d TiledResourcesTier=%d ConservativeRasterTier=%d "
               "TypedUAVLoadAdditionalFormats=%d ROVs=%d\n",
               (int)o.ResourceBindingTier, (int)o.TiledResourcesTier,
               (int)o.ConservativeRasterizationTier,
               (int)o.TypedUAVLoadAdditionalFormats, (int)o.ROVsSupported);

    D3D12_FEATURE_DATA_D3D12_OPTIONS5 o5 = {};
    if (SUCCEEDED(dev->CheckFeatureSupport(D3D12_FEATURE_D3D12_OPTIONS5, &o5, sizeof(o5))))
        printf("       caps: RaytracingTier=%d RenderPassesTier=%d\n",
               (int)o5.RaytracingTier, (int)o5.RenderPassesTier);

    LUID l = dev->GetAdapterLuid();
    printf("       caps: device reports AdapterLuid = %08lx:%08lx\n",
           (unsigned long)l.HighPart, (unsigned long)l.LowPart);
}

// Find the Helios adapter's LUID. Never assume index 0 (GATES.md G1 trap).
static bool find_helios_luid(LUID *out, wchar_t *name_out, size_t name_cch)
{
    IDXGIFactory1 *f = nullptr;
    if (FAILED(CreateDXGIFactory1(__uuidof(IDXGIFactory1), (void **)&f)))
        return false;

    bool found = false;
    IDXGIAdapter1 *a = nullptr;
    for (UINT i = 0; f->EnumAdapters1(i, &a) != DXGI_ERROR_NOT_FOUND; ++i) {
        DXGI_ADAPTER_DESC1 d;
        a->GetDesc1(&d);
        const bool software = (d.Flags & DXGI_ADAPTER_FLAG_SOFTWARE) != 0;
        printf("       adapter[%u] luid=%08lx:%08lx vendor=0x%04x device=0x%04x%s name=%ls\n",
               i, (unsigned long)d.AdapterLuid.HighPart, (unsigned long)d.AdapterLuid.LowPart,
               d.VendorId, d.DeviceId, software ? " SOFTWARE" : "", d.Description);
        // virtio-gpu is PCI\VEN_1AF4&DEV_1050.
        if (!found && !software && d.VendorId == 0x1af4) {
            *out = d.AdapterLuid;
            wcsncpy_s(name_out, name_cch, d.Description, _TRUNCATE);
            found = true;
        }
        a->Release();
        a = nullptr;
    }
    f->Release();
    return found;
}

int main(int argc, char **argv)
{
    const wchar_t *dll_path = DEFAULT_DLL;
    wchar_t dll_buf[MAX_PATH];
    if (argc > 1) {
        MultiByteToWideChar(CP_ACP, 0, argv[1], -1, dll_buf, MAX_PATH);
        dll_path = dll_buf;
    }

    printf("d3d12_bridge_probe — D12-G1 engine gate\n");
    printf("       engine dll = %ls\n", dll_path);

    // ---- 1. resolve the engine and BOTH Helios exports ----------------------
    HMODULE eng = LoadLibraryW(dll_path);
    if (!eng) { FAILSTEP("LoadLibraryW(%ls) -> GetLastError=%lu", dll_path, GetLastError()); return 1; }
    STEP("LoadLibraryW ok, base=%p", (void *)eng);

    wchar_t resolved[MAX_PATH] = {};
    GetModuleFileNameW(eng, resolved, MAX_PATH);
    printf("       loaded from = %ls\n", resolved);

    auto create_device = (PFN_HELIOS_VKD3D_CREATE_DEVICE)
            GetProcAddress(eng, "helios_vkd3d_create_device");
    auto serialize_rs = (PFN_HELIOS_VKD3D_SERIALIZE_ROOT_SIGNATURE)
            GetProcAddress(eng, "helios_vkd3d_serialize_root_signature");
    if (!create_device) { FAILSTEP("GetProcAddress(helios_vkd3d_create_device) -> %lu", GetLastError()); return 1; }
    if (!serialize_rs)  { FAILSTEP("GetProcAddress(helios_vkd3d_serialize_root_signature) -> %lu", GetLastError()); return 1; }
    STEP("both Helios exports resolved (create_device=%p serialize_root_signature=%p)",
         (void *)create_device, (void *)serialize_rs);

    // ---- 2. the adapter LUID (probe convenience, not the path under test) ----
    LUID luid = {};
    wchar_t adapter_name[128] = L"(none)";
    if (!find_helios_luid(&luid, adapter_name, ARRAYSIZE(adapter_name))) {
        FAILSTEP("no virtio-gpu (VEN_1AF4) adapter found via DXGI%s", "");
        return 1;
    }
    STEP("Helios adapter luid=%08lx:%08lx name=%ls",
         (unsigned long)luid.HighPart, (unsigned long)luid.LowPart, adapter_name);

    // ---- 3. the device, through the Helios export ---------------------------
    ID3D12Device *dev = nullptr;
    HRESULT hr = create_device(luid, __uuidof(ID3D12Device), (void **)&dev);
    if (!check(hr, "helios_vkd3d_create_device(IID_ID3D12Device)")) return 1;
    dump_caps(dev);

    // ---- 4. queue / allocator / list ----------------------------------------
    ID3D12CommandQueue *queue = nullptr;
    D3D12_COMMAND_QUEUE_DESC qd = {};
    qd.Type = D3D12_COMMAND_LIST_TYPE_DIRECT;
    if (!check(dev->CreateCommandQueue(&qd, __uuidof(ID3D12CommandQueue), (void **)&queue),
               "CreateCommandQueue(DIRECT)")) return 1;

    ID3D12CommandAllocator *alloc = nullptr;
    if (!check(dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,
               __uuidof(ID3D12CommandAllocator), (void **)&alloc), "CreateCommandAllocator")) return 1;

    // ---- 5. root signature THROUGH THE SECOND HELIOS EXPORT ------------------
    // This is the H3 re-serialization path umd12 must use: d3d12umddi delivers
    // root signatures already parsed, so the UMD re-serializes to an RTS0 blob.
    D3D12_ROOT_SIGNATURE_DESC rsd = {};
    rsd.Flags = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;
    ID3DBlob *rs_blob = nullptr, *rs_err = nullptr;
    if (!check(serialize_rs(&rsd, D3D_ROOT_SIGNATURE_VERSION_1, &rs_blob, &rs_err),
               "helios_vkd3d_serialize_root_signature")) {
        if (rs_err) printf("       serializer said: %.*s\n",
                           (int)rs_err->GetBufferSize(), (const char *)rs_err->GetBufferPointer());
        return 1;
    }
    ID3D12RootSignature *rs = nullptr;
    if (!check(dev->CreateRootSignature(0, rs_blob->GetBufferPointer(), rs_blob->GetBufferSize(),
               __uuidof(ID3D12RootSignature), (void **)&rs), "CreateRootSignature")) return 1;

    // ---- 6. PSO with the DXIL SM 6.0 shaders --------------------------------
    D3D12_INPUT_ELEMENT_DESC il[] = {
        { "POSITION", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 0,  D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
        { "COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 16, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
    };
    D3D12_GRAPHICS_PIPELINE_STATE_DESC pd = {};
    pd.pRootSignature = rs;
    pd.VS = { g_vs_main, sizeof(g_vs_main) };
    pd.PS = { g_ps_main, sizeof(g_ps_main) };
    pd.InputLayout = { il, ARRAYSIZE(il) };
    pd.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
    pd.RasterizerState.FillMode = D3D12_FILL_MODE_SOLID;
    pd.RasterizerState.CullMode = D3D12_CULL_MODE_NONE;
    pd.RasterizerState.DepthClipEnable = TRUE;
    pd.BlendState.RenderTarget[0].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;
    pd.DepthStencilState.DepthEnable = FALSE;
    pd.DepthStencilState.StencilEnable = FALSE;
    pd.SampleMask = UINT_MAX;
    pd.NumRenderTargets = 1;
    pd.RTVFormats[0] = DXGI_FORMAT_R8G8B8A8_UNORM;
    pd.SampleDesc.Count = 1;
    ID3D12PipelineState *pso = nullptr;
    if (!check(dev->CreateGraphicsPipelineState(&pd, __uuidof(ID3D12PipelineState), (void **)&pso),
               "CreateGraphicsPipelineState (DXIL SM 6.0 vs+ps)")) return 1;

    ID3D12GraphicsCommandList *cl = nullptr;
    if (!check(dev->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT, alloc, pso,
               __uuidof(ID3D12GraphicsCommandList), (void **)&cl), "CreateCommandList")) return 1;

    // ---- 7. the render target, the vertex buffer, the readback buffer -------
    D3D12_HEAP_PROPERTIES hp_default = { D3D12_HEAP_TYPE_DEFAULT };
    D3D12_HEAP_PROPERTIES hp_upload  = { D3D12_HEAP_TYPE_UPLOAD };
    D3D12_HEAP_PROPERTIES hp_read    = { D3D12_HEAP_TYPE_READBACK };

    D3D12_RESOURCE_DESC rt_desc = {};
    rt_desc.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
    rt_desc.Width = RT_W; rt_desc.Height = RT_H;
    rt_desc.DepthOrArraySize = 1; rt_desc.MipLevels = 1;
    rt_desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    rt_desc.SampleDesc.Count = 1;
    rt_desc.Layout = D3D12_TEXTURE_LAYOUT_UNKNOWN;
    rt_desc.Flags = D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET;

    D3D12_CLEAR_VALUE cv = {};
    cv.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    memcpy(cv.Color, CLEAR_RGBA, sizeof(CLEAR_RGBA));

    ID3D12Resource *rt = nullptr;
    if (!check(dev->CreateCommittedResource(&hp_default, D3D12_HEAP_FLAG_NONE, &rt_desc,
               D3D12_RESOURCE_STATE_RENDER_TARGET, &cv, __uuidof(ID3D12Resource), (void **)&rt),
               "CreateCommittedResource(DEFAULT, R8G8B8A8_UNORM 256x256, RENDER_TARGET)")) return 1;

    D3D12_PLACED_SUBRESOURCE_FOOTPRINT fp = {};
    UINT rows = 0; UINT64 row_bytes = 0, total = 0;
    dev->GetCopyableFootprints(&rt_desc, 0, 1, 0, &fp, &rows, &row_bytes, &total);
    printf("       readback footprint: rowpitch=%u rows=%u total=%llu\n",
           fp.Footprint.RowPitch, rows, (unsigned long long)total);

    D3D12_RESOURCE_DESC buf_desc = {};
    buf_desc.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
    buf_desc.Height = 1; buf_desc.DepthOrArraySize = 1; buf_desc.MipLevels = 1;
    buf_desc.Format = DXGI_FORMAT_UNKNOWN;
    buf_desc.SampleDesc.Count = 1;
    buf_desc.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;

    buf_desc.Width = total;
    ID3D12Resource *rb = nullptr;
    if (!check(dev->CreateCommittedResource(&hp_read, D3D12_HEAP_FLAG_NONE, &buf_desc,
               D3D12_RESOURCE_STATE_COPY_DEST, nullptr, __uuidof(ID3D12Resource), (void **)&rb),
               "CreateCommittedResource(READBACK)")) return 1;

    const Vertex verts[3] = {
        { {  0.0f,  0.5f, 0.0f, 1.0f }, { 1.0f, 128.0f / 255.0f, 64.0f / 255.0f, 1.0f } },
        { {  0.5f, -0.5f, 0.0f, 1.0f }, { 1.0f, 128.0f / 255.0f, 64.0f / 255.0f, 1.0f } },
        { { -0.5f, -0.5f, 0.0f, 1.0f }, { 1.0f, 128.0f / 255.0f, 64.0f / 255.0f, 1.0f } },
    };
    buf_desc.Width = sizeof(verts);
    ID3D12Resource *vb = nullptr;
    if (!check(dev->CreateCommittedResource(&hp_upload, D3D12_HEAP_FLAG_NONE, &buf_desc,
               D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, __uuidof(ID3D12Resource), (void **)&vb),
               "CreateCommittedResource(UPLOAD, vertex buffer)")) return 1;
    {
        void *p = nullptr;
        D3D12_RANGE none = { 0, 0 };
        if (!check(vb->Map(0, &none, &p), "Map(vertex buffer)")) return 1;
        memcpy(p, verts, sizeof(verts));
        vb->Unmap(0, nullptr);
    }

    ID3D12DescriptorHeap *rtv_heap = nullptr;
    D3D12_DESCRIPTOR_HEAP_DESC hd = {};
    hd.Type = D3D12_DESCRIPTOR_HEAP_TYPE_RTV;
    hd.NumDescriptors = 1;
    if (!check(dev->CreateDescriptorHeap(&hd, __uuidof(ID3D12DescriptorHeap), (void **)&rtv_heap),
               "CreateDescriptorHeap(RTV)")) return 1;
    D3D12_CPU_DESCRIPTOR_HANDLE rtv = rtv_heap->GetCPUDescriptorHandleForHeapStart();
    dev->CreateRenderTargetView(rt, nullptr, rtv);
    STEP("CreateRenderTargetView ok (rtv.ptr=0x%llx, RTV stride=%u)",
         (unsigned long long)rtv.ptr, dev->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_RTV));

    // ---- 8. record ----------------------------------------------------------
    D3D12_VIEWPORT vp = { 0.0f, 0.0f, (float)RT_W, (float)RT_H, 0.0f, 1.0f };
    D3D12_RECT sc = { 0, 0, (LONG)RT_W, (LONG)RT_H };
    D3D12_VERTEX_BUFFER_VIEW vbv = { vb->GetGPUVirtualAddress(), sizeof(verts), sizeof(Vertex) };

    cl->SetGraphicsRootSignature(rs);
    cl->RSSetViewports(1, &vp);
    cl->RSSetScissorRects(1, &sc);
    cl->OMSetRenderTargets(1, &rtv, FALSE, nullptr);
    cl->ClearRenderTargetView(rtv, CLEAR_RGBA, 0, nullptr);
    cl->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    cl->IASetVertexBuffers(0, 1, &vbv);
    cl->DrawInstanced(3, 1, 0, 0);

    D3D12_RESOURCE_BARRIER b = {};
    b.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
    b.Transition.pResource = rt;
    b.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
    b.Transition.StateBefore = D3D12_RESOURCE_STATE_RENDER_TARGET;
    b.Transition.StateAfter = D3D12_RESOURCE_STATE_COPY_SOURCE;
    cl->ResourceBarrier(1, &b);

    D3D12_TEXTURE_COPY_LOCATION src = {}, dst = {};
    src.pResource = rt; src.Type = D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX; src.SubresourceIndex = 0;
    dst.pResource = rb; dst.Type = D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT; dst.PlacedFootprint = fp;
    cl->CopyTextureRegion(&dst, 0, 0, 0, &src, nullptr);

    if (!check(cl->Close(), "command list Close")) return 1;

    // ---- 9. submit and wait -------------------------------------------------
    ID3D12CommandList *lists[] = { cl };
    queue->ExecuteCommandLists(1, lists);
    STEP("ExecuteCommandLists submitted%s", "");

    ID3D12Fence *fence = nullptr;
    if (!check(dev->CreateFence(0, D3D12_FENCE_FLAG_NONE, __uuidof(ID3D12Fence), (void **)&fence),
               "CreateFence")) return 1;
    HANDLE ev = CreateEventW(nullptr, FALSE, FALSE, nullptr);
    if (!check(queue->Signal(fence, 1), "queue->Signal(1)")) return 1;
    if (!check(fence->SetEventOnCompletion(1, ev), "SetEventOnCompletion")) return 1;
    DWORD w = WaitForSingleObject(ev, 10000);
    if (w != WAIT_OBJECT_0) { FAILSTEP("fence wait -> %lu (completed=%llu)", w,
                                       (unsigned long long)fence->GetCompletedValue()); return 1; }
    STEP("fence signalled, completed=%llu", (unsigned long long)fence->GetCompletedValue());

    // ---- 10. read the pixels back and compare -------------------------------
    BYTE *px = nullptr;
    D3D12_RANGE whole = { 0, (SIZE_T)total };
    if (!check(rb->Map(0, &whole, (void **)&px), "Map(readback)")) return 1;

    struct Sample { const char *what; UINT x, y; const BYTE *expect; };
    const Sample samples[] = {
        { "top-left corner  (outside the triangle) == clear colour", 4,   4,   EXPECT_CLEAR },
        { "top-right corner (outside the triangle) == clear colour", 251, 4,   EXPECT_CLEAR },
        { "bottom-left      (outside the triangle) == clear colour", 4,   251, EXPECT_CLEAR },
        { "centre           (inside  the triangle) == vertex colour", 128, 160, EXPECT_TRI },
        { "lower-centre     (inside  the triangle) == vertex colour", 128, 180, EXPECT_TRI },
    };
    for (int i = 0; i < ARRAYSIZE(samples); i++) {
        const BYTE *p = px + (size_t)samples[i].y * fp.Footprint.RowPitch + (size_t)samples[i].x * 4;
        bool ok = true;
        for (int c = 0; c < 4; c++) {
            int d = (int)p[c] - (int)samples[i].expect[c];
            if (d < -1 || d > 1) ok = false;
        }
        if (ok)
            printf("[%02d] ok    %s  (%u,%u)=%u,%u,%u,%u\n", ++g_step, samples[i].what,
                   samples[i].x, samples[i].y, p[0], p[1], p[2], p[3]);
        else {
            printf("[%02d] FAIL  %s  (%u,%u)=%u,%u,%u,%u expected %u,%u,%u,%u\n", ++g_step,
                   samples[i].what, samples[i].x, samples[i].y, p[0], p[1], p[2], p[3],
                   samples[i].expect[0], samples[i].expect[1], samples[i].expect[2], samples[i].expect[3]);
            g_failures++;
        }
    }
    D3D12_RANGE none = { 0, 0 };
    rb->Unmap(0, &none);

    printf("\nD12-G1 %s — %d failure(s) across %d steps\n",
           g_failures ? "FAIL" : "PASS", g_failures, g_step);

    // Release in reverse order; a clean teardown is part of the gate (a hang or
    // a crash here is a real finding for the UMD, which tears devices down
    // constantly — see the six-handles-per-device leak, memory 54th).
    CloseHandle(ev);
    fence->Release(); rtv_heap->Release(); vb->Release(); rb->Release(); rt->Release();
    cl->Release(); pso->Release(); rs->Release(); rs_blob->Release(); if (rs_err) rs_err->Release();
    alloc->Release(); queue->Release();
    ULONG left = dev->Release();
    printf("       device final Release() -> refcount %lu (0 expected)\n", left);
    if (left != 0) g_failures++;

    return g_failures ? 1 : 0;
}
