param(
    [Parameter(Position = 0, ValueFromRemainingArguments = $true)]
    [string[]]$Command = @(),
    [string]$GameExe = "",
    [string[]]$GameArgs = @(),
    [ValidateSet("auto", "x86", "x64")]
    [string]$Arch = "auto",
    [string]$DxvkRoot = "Z:\dxvk",
    [string]$Vkd3dRoot = "Z:\vkd3d-proton",
    [string]$DxvkDir = "",
    [string]$Vkd3dDir = "",
    [string]$Manifest = "C:\ProgramData\HeliosVulkan\virtio_devenv_icd.x86_64.json",
    [string]$ConfigFile = "",
    [switch]$NoInstallDlls,
    [string[]]$Apis = @("d3d8", "d3d9", "d3d10", "d3d11", "d3d12"),
    [switch]$PrintSteamCommand,
    [switch]$NoLocalRedirectFile,
    [switch]$AllowFse,
    [switch]$QuietDxvk,
    [switch]$InstallOnly,
    [switch]$Wait
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ($PrintSteamCommand) {
    $cmdPath = [System.IO.Path]::ChangeExtension($PSCommandPath, ".cmd")
    Write-Output "`"$cmdPath`" %command%"
    return
}

if (-not $GameExe -and $Command.Count -gt 0) {
    $GameExe = $Command[0]
    if ($Command.Count -gt 1) {
        $GameArgs = $Command[1..($Command.Count - 1)]
    }
}

if (-not $GameExe) {
    $cmdPath = [System.IO.Path]::ChangeExtension($PSCommandPath, ".cmd")
    throw "Provide -GameExe, pass <exe> [args], or use this as a Steam launch option with: `"$cmdPath`" %command%"
}

if (-not (Test-Path -LiteralPath $GameExe -PathType Leaf)) {
    throw "Game executable not found: $GameExe"
}

if (-not (Test-Path -LiteralPath $Manifest -PathType Leaf)) {
    throw "Helios Vulkan ICD manifest not found: $Manifest"
}

$gamePath = (Resolve-Path -LiteralPath $GameExe).Path
$gameDir = Split-Path -Parent $gamePath
$repoRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)

function Resolve-RepoPath {
    param([string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }

    return Join-Path $repoRoot $Path
}

function Get-PeArch {
    param([string]$Path)

    $fs = [System.IO.File]::Open($Path, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
    try {
        $br = New-Object System.IO.BinaryReader($fs)
        $fs.Seek(0x3c, [System.IO.SeekOrigin]::Begin) | Out-Null
        $peOffset = $br.ReadInt32()
        $fs.Seek($peOffset, [System.IO.SeekOrigin]::Begin) | Out-Null
        $signature = $br.ReadUInt32()
        if ($signature -ne 0x00004550) {
            throw "Not a PE executable: $Path"
        }

        $machine = $br.ReadUInt16()
        switch ($machine) {
            0x8664 { return "x64" }
            0x014c { return "x86" }
            default { throw ("Unsupported PE machine 0x{0:x4}: {1}" -f $machine, $Path) }
        }
    }
    finally {
        $fs.Dispose()
    }
}

if ($Arch -eq "auto") {
    $Arch = Get-PeArch -Path $gamePath
}

if (-not $DxvkDir) {
    $dxvkSubdir = if ($Arch -eq "x86") { "x32" } else { "x64" }
    $DxvkDir = Join-Path (Resolve-RepoPath $DxvkRoot) $dxvkSubdir
}

if (-not $Vkd3dDir) {
    $vkd3dSubdir = if ($Arch -eq "x86") { "x86" } else { "x64" }
    $Vkd3dDir = Join-Path (Resolve-RepoPath $Vkd3dRoot) $vkd3dSubdir
}

function Copy-RequiredDll {
    param(
        [string]$SourceDir,
        [string]$Name
    )

    $src = Join-Path $SourceDir $Name
    if (-not (Test-Path -LiteralPath $src -PathType Leaf)) {
        throw "Missing translated D3D DLL: $src"
    }

    Copy-Item -LiteralPath $src -Destination (Join-Path $gameDir $Name) -Force
}

if (-not $NoInstallDlls) {
    $apiSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    foreach ($api in $Apis) {
        [void]$apiSet.Add($api)
    }

    if ($apiSet.Contains("d3d8")) {
        Copy-RequiredDll -SourceDir $DxvkDir -Name "d3d8.dll"
    }
    if ($apiSet.Contains("d3d9")) {
        Copy-RequiredDll -SourceDir $DxvkDir -Name "d3d9.dll"
    }
    if ($apiSet.Contains("d3d10")) {
        Copy-RequiredDll -SourceDir $DxvkDir -Name "d3d10core.dll"
        Copy-RequiredDll -SourceDir $DxvkDir -Name "d3d11.dll"
        Copy-RequiredDll -SourceDir $DxvkDir -Name "dxgi.dll"
    }
    if ($apiSet.Contains("d3d11")) {
        Copy-RequiredDll -SourceDir $DxvkDir -Name "d3d11.dll"
        Copy-RequiredDll -SourceDir $DxvkDir -Name "dxgi.dll"
    }
    if ($apiSet.Contains("d3d12")) {
        Copy-RequiredDll -SourceDir $Vkd3dDir -Name "d3d12.dll"
        Copy-RequiredDll -SourceDir $Vkd3dDir -Name "d3d12core.dll"
        Copy-RequiredDll -SourceDir $DxvkDir -Name "dxgi.dll"
    }

    if (-not $NoLocalRedirectFile) {
        New-Item -ItemType File -Force -Path "$gamePath.local" | Out-Null
    }
}

if (-not $ConfigFile) {
    $ConfigFile = Join-Path $gameDir "dxvk.conf"
}

if (-not (Test-Path -LiteralPath $ConfigFile -PathType Leaf)) {
    @(
        "# Generated by launch-translated-d3d-game.ps1",
        ("dxvk.allowFse = {0}" -f ($(if ($AllowFse) { "True" } else { "False" }))),
        "dxgi.maxSharedMemory = 0"
    ) | Set-Content -LiteralPath $ConfigFile -Encoding ascii
}

if ($InstallOnly) {
    Write-Output "Installed translated D3D files:"
    Write-Output "  GameExe=$gamePath"
    Write-Output "  Arch=$Arch"
    Write-Output "  DXVK_CONFIG_FILE=$ConfigFile"
    Write-Output "  DXVK source=$DxvkDir"
    Write-Output "  VKD3D-Proton source=$Vkd3dDir"
    Write-Output "  DLL target=$gameDir"
    return
}

$oldVkDriverFiles = $env:VK_DRIVER_FILES
$oldVkIcdFilenames = $env:VK_ICD_FILENAMES
$oldDxvkConfig = $env:DXVK_CONFIG_FILE
$oldDxvkLogLevel = $env:DXVK_LOG_LEVEL
$oldVkLoaderDebug = $env:VK_LOADER_DEBUG

try {
    $env:VK_DRIVER_FILES = $Manifest
    $env:VK_ICD_FILENAMES = $Manifest
    $env:DXVK_CONFIG_FILE = $ConfigFile
    $env:DXVK_LOG_LEVEL = if ($QuietDxvk) { "none" } else { "info" }

    Write-Output "Launching with translated D3D:"
    Write-Output "  GameExe=$gamePath"
    Write-Output "  Arch=$Arch"
    Write-Output "  VK_DRIVER_FILES=$env:VK_DRIVER_FILES"
    Write-Output "  DXVK_CONFIG_FILE=$env:DXVK_CONFIG_FILE"
    Write-Output "  DXVK source=$DxvkDir"
    Write-Output "  VKD3D-Proton source=$Vkd3dDir"
    Write-Output "  DLL target=$gameDir"

    if ($Wait) {
        & $gamePath @GameArgs
        exit $LASTEXITCODE
    }

    Start-Process -FilePath $gamePath -ArgumentList $GameArgs -WorkingDirectory $gameDir
}
finally {
    $env:VK_DRIVER_FILES = $oldVkDriverFiles
    $env:VK_ICD_FILENAMES = $oldVkIcdFilenames
    $env:DXVK_CONFIG_FILE = $oldDxvkConfig
    $env:DXVK_LOG_LEVEL = $oldDxvkLogLevel
    $env:VK_LOADER_DEBUG = $oldVkLoaderDebug
}
